import { z } from "zod";

export const EGYPTIAN_CONTEXT_VECTORS = [
  "WhatsApp Family Medical Panic",
  "Religious/Fatwa Manipulation",
  "State Stability & Economic Rumors",
  "Pseudoscience Healthcare Scams",
  "Dietary & Herbal Misinformation",
  "Sectarian Tension Generation",
  "Educational Panic",
  "Infrastructure & Public Service Panic",
  "Vaccine & Epidemic Conspiracies",
  "Historical Revisionism",
  "Cultural Heritage Distortion",
  "Social Engineering & Astroturfing",
  "Financial & Currency Panic",
  "Generational Fear-Mongering",
  "Agricultural & Food Safety Panic",
  "Consumer Product Toxicity Claims",
  "Government Subsidy Rumors",
  "Employment & Labor Panic",
  "Youth & Morality Panics",
  "Cybersecurity & Privacy Hoaxes",
  "Weather & Climate Doomsday",
  "Supernatural & Jinn Attributions",
  "Foreign Interference Claims",
] as const;

export const NEGATIVE_SCIENCE_CATEGORIES = [
  "Core Scientific Fraud",
  "Statistical Cherry-Picking",
  "Logical Fallacies",
  "Pseudoscience Scams",
  "Survivorship Bias",
  "Correlation vs. Causation Fallacy",
  "Appeal to Emotion / Fear-Mongering",
  "False Authority / Fake Experts",
  "Anecdotal Evidence Over-reliance",
  "Out-of-Context Quotes",
  "Post Hoc Rationalization",
  "False Dichotomy",
  "Burden of Proof Reversal"
] as const;

export const VERBAL_SCIENCE_LAYERS = [
  "Emotional Trigger Analysis",
  "Source Provenance Check",
  "Logical Structure Validation",
  "Empirical Evidence Mapping",
  "Incentive & Bias Expose"
] as const;

export const EgyptianContextVectorSchema = z.enum(EGYPTIAN_CONTEXT_VECTORS);
export type EgyptianContextVector = z.infer<typeof EgyptianContextVectorSchema>;

export const NegativeScienceCategorySchema = z.enum(NEGATIVE_SCIENCE_CATEGORIES);
export type NegativeScienceCategory = z.infer<typeof NegativeScienceCategorySchema>;

export const DefenseCategorySchema = z.enum(["Medical", "DeepReal", "Demographic"]);
export type DefenseCategory = z.infer<typeof DefenseCategorySchema>;

export const DefenseMethodSchema = z.object({
  id: z.string(),
  category: DefenseCategorySchema,
  name: z.string(),
  description: z.string()
});
export type DefenseMethod = z.infer<typeof DefenseMethodSchema>;

export const DEFENSE_METHODS: DefenseMethod[] = [
  // MEDICAL (44)
  { id: "MED-001", category: "Medical", name: "Ministry of Health Alert Cross-Reference", description: "Check claims against the official Egyptian Ministry of Health Facebook page and website." },
  { id: "MED-002", category: "Medical", name: "WHO Egypt Bulletin Verification", description: "Verify local disease outbreak rumors with the World Health Organization's Egypt office updates." },
  { id: "MED-003", category: "Medical", name: "Doctors Syndicate License Query", description: "Verify the credentials of an alleged expert claiming a miracle cure via the Egyptian Medical Syndicate registry." },
  { id: "MED-004", category: "Medical", name: "Pharmacists Syndicate Drug Check", description: "Cross-reference claimed drug shortages or miracle supplements with Pharmacists Syndicate statements." },
  { id: "MED-005", category: "Medical", name: "EDA Registration Validation", description: "Check if a marketed health product or cosmetic is legally registered with the Egyptian Drug Authority (EDA)." },
  { id: "MED-006", category: "Medical", name: "WhatsApp Audio Provenance Trace", description: "Identify if a circulating 'doctor voice note' has been previously debunked on fact-checking platforms like Matsda2sh." },
  { id: "MED-007", category: "Medical", name: "Herbal Toxicity Literature Search", description: "Investigate popular local herbal remedies (e.g., specific Atwood blends) for known hepatotoxic effects." },
  { id: "MED-008", category: "Medical", name: "Vaccine Batch Tracking", description: "Debunk rumors of 'expired vaccines' by explaining the lot number tracking system used in Egyptian public clinics." },
  { id: "MED-009", category: "Medical", name: "Hospital Capacity Fact-Check", description: "Address rumors of overflowing local hospitals by citing direct statements from governorate health directorates." },
  { id: "MED-010", category: "Medical", name: "Ambulance Authority Log Review", description: "Counter false reports of mass casualties or ambulance delays using statements from the Egyptian Ambulance Authority." },
  { id: "MED-011", category: "Medical", name: "Clinical Trial Status Verification", description: "Check if a claimed 'Egyptian cure' is actually undergoing registered clinical trials on ClinicalTrials.gov or local registries." },
  { id: "MED-012", category: "Medical", name: "Blood Bank Inventory Check", description: "Verify viral posts claiming critical blood shortages at regional branches of the National Blood Transfusion Services." },
  { id: "MED-013", category: "Medical", name: "Infectious Disease Protocol Check", description: "Compare rumored quarantine measures against published national protocols for infectious disease management." },
  { id: "MED-014", category: "Medical", name: "Poison Control Center Advisory Search", description: "Consult Ain Shams University Poison Control Center for alerts on toxic food/drink trends circulating on TikTok." },
  { id: "MED-015", category: "Medical", name: "Radiology Image Reverse Search", description: "Use reverse image search to prove that an X-ray or MRI shared as a 'rare local case' is actually an old stock photo." },
  { id: "MED-016", category: "Medical", name: "Peer-Reviewed Literature Match", description: "Cross-reference sensational medical claims in local media with established scientific consensus in PubMed." },
  { id: "MED-017", category: "Medical", name: "Maternal Health Guideline Verification", description: "Address pregnancy myths shared in Facebook groups by linking to official maternal care guidelines." },
  { id: "MED-018", category: "Medical", name: "Pediatric Milestone Fact-Check", description: "Debunk alarming claims about child development delays caused by specific local foods." },
  { id: "MED-019", category: "Medical", name: "Dietary Supplement Content Analysis", description: "Check the active ingredients of heavily marketed 'weight loss' products against prohibited substance lists." },
  { id: "MED-020", category: "Medical", name: "Cancer Treatment Misinformation Debunk", description: "Counter claims that alternative therapies can replace chemotherapy, referencing the National Cancer Institute in Cairo." },
  { id: "MED-021", category: "Medical", name: "Organ Trafficking Rumor Assessment", description: "Investigate viral stories of organ theft by checking official Ministry of Interior and hospital denial statements." },
  { id: "MED-022", category: "Medical", name: "Water Borne Disease Rumor Check", description: "Verify claims of contaminated drinking water in specific governorates with the Holding Company for Water and Wastewater." },
  { id: "MED-023", category: "Medical", name: "Food Poisoning Outbreak Verification", description: "Cross-check rumors of mass food poisoning at schools or restaurants with official health inspector reports." },
  { id: "MED-024", category: "Medical", name: "Zoonotic Disease Tracking", description: "Debunk rumors of animal-to-human disease jumps (e.g., avian flu panics) with Ministry of Agriculture data." },
  { id: "MED-025", category: "Medical", name: "Psychiatric Misdiagnosis Clarification", description: "Address the misattribution of psychiatric disorders to 'Jinn' or 'Evil Eye' by providing evidence-based mental health resources." },
  { id: "MED-026", category: "Medical", name: "Cosmetic Procedure Safety Check", description: "Highlight the risks of unregulated cosmetic clinics operating without proper oversight." },
  { id: "MED-027", category: "Medical", name: "Dental Health Mythbusting", description: "Debunk dangerous DIY dental treatments popularized on social media." },
  { id: "MED-028", category: "Medical", name: "Optometry Scams Identification", description: "Expose fraudulent 'vision-correcting' eye drops sold online." },
  { id: "MED-029", category: "Medical", name: "Hearing Loss Cure Debunking", description: "Counter fake claims of immediate cures for sensorineural hearing loss." },
  { id: "MED-030", category: "Medical", name: "Dermatological Fad Safety Review", description: "Analyze the safety of trending skin-bleaching or acne treatments using dermatological consensus." },
  { id: "MED-031", category: "Medical", name: "Endocrinology Myth Verification", description: "Address misconceptions about diabetes management and insulin replacement therapies." },
  { id: "MED-032", category: "Medical", name: "Cardiovascular Emergency Rumor Check", description: "Debunk viral posts claiming sudden cardiac arrests are linked to specific brands of cooking oil." },
  { id: "MED-033", category: "Medical", name: "Respiratory Illness Trend Analysis", description: "Clarify the difference between seasonal flu and new viral strains to prevent unnecessary panic." },
  { id: "MED-034", category: "Medical", name: "Gastrointestinal Cure Fact-Check", description: "Investigate claims that a specific local food cures severe GI tract infections." },
  { id: "MED-035", category: "Medical", name: "Neurological Disorder Stigma Reduction", description: "Debunk myths that epilepsy is contagious or a sign of spiritual possession." },
  { id: "MED-036", category: "Medical", name: "Orthopedic Miracle Cure Debunking", description: "Expose fraudulent joint-pain supplements targeting the elderly population." },
  { id: "MED-037", category: "Medical", name: "Rheumatology Misinformation Check", description: "Counter claims that completely cutting out certain food groups cures autoimmune diseases." },
  { id: "MED-038", category: "Medical", name: "Nephrology Diet Mythbusting", description: "Address dangerous hydration or dietary advice targeting kidney disease patients." },
  { id: "MED-039", category: "Medical", name: "Urology Scam Identification", description: "Debunk fake herbal remedies for kidney stones or other urological conditions." },
  { id: "MED-040", category: "Medical", name: "Gynecological Health Fact-Check", description: "Counter myths surrounding fertility treatments and reproductive health." },
  { id: "MED-041", category: "Medical", name: "Neonatal Care Misinformation Check", description: "Address dangerous home remedies for jaundice or other neonatal conditions." },
  { id: "MED-042", category: "Medical", name: "Geriatric Health Scam Exposure", description: "Expose scams specifically targeting the fears of the aging population regarding memory loss." },
  { id: "MED-043", category: "Medical", name: "Pain Management Mythbusting", description: "Debunk claims that certain chronic pain conditions are purely psychological." },
  { id: "MED-044", category: "Medical", name: "Alternative Medicine Efficacy Review", description: "Provide evidence-based reviews of popular alternative therapies like Hijama (cupping) for specific conditions." },

  // DEEPREAL (43)
  { id: "DPR-001", category: "DeepReal", name: "AI Image Artifact Detection", description: "Analyze suspected deepfake images for common AI generation artifacts like distorted hands or mismatched earrings." },
  { id: "DPR-002", category: "DeepReal", name: "Audio Deepfake Frequency Analysis", description: "Examine voice notes for unnatural pitch shifts or robotic cadence typical of AI voice cloning." },
  { id: "DPR-003", category: "DeepReal", name: "Video Lip-Sync Inconsistency Check", description: "Check if a politician's lip movements match the audio track in a viral video." },
  { id: "DPR-004", category: "DeepReal", name: "Metadata Extraction & Review", description: "Extract EXIF data from photos to determine original creation dates and software used." },
  { id: "DPR-005", category: "DeepReal", name: "Reverse Image Search (Global)", description: "Use Google, TinEye, and Yandex to find the original source of an out-of-context image." },
  { id: "DPR-006", category: "DeepReal", name: "Reverse Video Frame Search", description: "Extract keyframes from a video and search them to identify recycled footage from older events." },
  { id: "DPR-007", category: "DeepReal", name: "Shadow & Lighting Consistency Analysis", description: "Analyze the direction of shadows and lighting in an image to detect copy-pasted elements." },
  { id: "DPR-008", category: "DeepReal", name: "Geolocation Verification", description: "Verify the claimed location of a video using Google Earth and local landmarks." },
  { id: "DPR-009", category: "DeepReal", name: "Weather Data Cross-Reference", description: "Check historical weather data to confirm if a video claiming to be from yesterday matches the actual weather." },
  { id: "DPR-010", category: "DeepReal", name: "Linguistic Anomaly Detection", description: "Identify dialect or slang inconsistencies in a text or audio clip claiming to be from a specific Egyptian region." },
  { id: "DPR-011", category: "DeepReal", name: "Bot Network Identification", description: "Analyze social media metrics to detect coordinated inauthentic behavior amplifying a post." },
  { id: "DPR-012", category: "DeepReal", name: "Account History Audit", description: "Review the posting history of an account to determine if it is a repurposed purchased account." },
  { id: "DPR-013", category: "DeepReal", name: "Deepfake Detection Software Sweep", description: "Run media through specialized AI detection tools to get a probability score of synthetic generation." },
  { id: "DPR-014", category: "DeepReal", name: "Source Code Inspection", description: "Inspect the source code of a suspicious website for copied templates or hidden malicious scripts." },
  { id: "DPR-015", category: "DeepReal", name: "Domain Registration Lookup", description: "Use WHOIS lookups to find the registration date and owner of a website spreading fake news." },
  { id: "DPR-016", category: "DeepReal", name: "URL Redirection Tracing", description: "Trace the path of shortened URLs to uncover the final destination and potential affiliate links." },
  { id: "DPR-017", category: "DeepReal", name: "Phishing Scam Identification", description: "Analyze the design and language of a message for common phishing tactics (urgency, typos)." },
  { id: "DPR-018", category: "DeepReal", name: "Official Channel Cross-Check", description: "Verify announcements against the official verified social media channels of the entity involved." },
  { id: "DPR-019", category: "DeepReal", name: "Crowdsourced Fact-Checking Review", description: "Consult community notes on X (Twitter) or specialized Egyptian fact-checking initiatives." },
  { id: "DPR-020", category: "DeepReal", name: "Synthetic Text Detection", description: "Analyze articles for repetitive structures and lack of nuance typical of LLM-generated content." },
  { id: "DPR-021", category: "DeepReal", name: "Voice Modulation Check", description: "Detect simple pitch shifting or speed alteration used to disguise a speaker's identity." },
  { id: "DPR-022", category: "DeepReal", name: "Background Noise Analysis", description: "Analyze audio for inconsistent background noise that suggests splicing or studio recording." },
  { id: "DPR-023", category: "DeepReal", name: "Visual Crowd Duplication Detection", description: "Identify repeating patterns in photos of crowds indicating digital multiplication." },
  { id: "DPR-024", category: "DeepReal", name: "Signage & Text Translation", description: "Translate background signs in a video to confirm the actual country of origin." },
  { id: "DPR-025", category: "DeepReal", name: "Uniform & Insignia Verification", description: "Verify the accuracy of military or police uniforms in images claiming to show Egyptian forces." },
  { id: "DPR-026", category: "DeepReal", name: "Vehicle License Plate Check", description: "Analyze license plate formats in a video to confirm if they match Egyptian standards." },
  { id: "DPR-027", category: "DeepReal", name: "Architectural Style Matching", description: "Compare building styles in an image with typical Egyptian architecture to verify location." },
  { id: "DPR-028", category: "DeepReal", name: "Street Furniture Analysis", description: "Check details like streetlights or trash cans which vary significantly between countries." },
  { id: "DPR-029", category: "DeepReal", name: "Sun Position Calculation", description: "Calculate the expected sun angle for a given time and location to verify shadows." },
  { id: "DPR-030", category: "DeepReal", name: "Reflection Consistency Check", description: "Ensure reflections in windows or water match the objects in front of them." },
  { id: "DPR-031", category: "DeepReal", name: "Frame-by-Frame Video Review", description: "Watch a video frame-by-frame to catch hidden cuts or momentary glitches." },
  { id: "DPR-032", category: "DeepReal", name: "Audio-Video Sync Analysis", description: "Measure the precise delay between audio and visual events (like a clap) to detect tampering." },
  { id: "DPR-033", category: "DeepReal", name: "Compression Artifact Analysis", description: "Differentiate between natural compression artifacts and those caused by digital manipulation." },
  { id: "DPR-034", category: "DeepReal", name: "Social Engineering Tactic Identification", description: "Recognize manipulative language designed to trigger outrage and sharing without verification." },
  { id: "DPR-035", category: "DeepReal", name: "Emotional Manipulation Analysis", description: "Assess how a piece of media is designed to evoke fear, anger, or sympathy." },
  { id: "DPR-036", category: "DeepReal", name: "Financial Scam Typology Matching", description: "Compare a suspicious investment offer against known Ponzi scheme or crypto scam patterns." },
  { id: "DPR-037", category: "DeepReal", name: "Fake Review Detection", description: "Identify patterns of fake reviews on e-commerce sites or app stores." },
  { id: "DPR-038", category: "DeepReal", name: "Sockpuppet Account Identification", description: "Link multiple fake accounts controlled by a single entity based on behavior and IP." },
  { id: "DPR-039", category: "DeepReal", name: "Echo Chamber Mapping", description: "Map how a piece of disinformation circulates within specific, closed online communities." },
  { id: "DPR-040", category: "DeepReal", name: "Hashtag Manipulation Tracking", description: "Analyze the sudden emergence of a hashtag to determine if it's organically driven or artificially inflated." },
  { id: "DPR-041", category: "DeepReal", name: "Algorithm Exploitation Analysis", description: "Identify techniques used to game social media algorithms to increase visibility." },
  { id: "DPR-042", category: "DeepReal", name: "Disinformation Narrative Tracking", description: "Trace the evolution of a false narrative over time and across different platforms." },
  { id: "DPR-043", category: "DeepReal", name: "Threat Actor Attribution", description: "Link a disinformation campaign to a known state or non-state actor based on TTPs (Tactics, Techniques, and Procedures)." },

  // DEMOGRAPHIC (43)
  { id: "DEM-001", category: "Demographic", name: "CAPMAS Data Cross-Reference", description: "Verify population, inflation, or employment statistics against official CAPMAS reports." },
  { id: "DEM-002", category: "Demographic", name: "Sectarian Bias Neutralization", description: "Identify and deconstruct narratives designed to create division between Muslims and Christians." },
  { id: "DEM-003", category: "Demographic", name: "Historical Contextualization", description: "Provide accurate historical background to counter revisionist claims about Egyptian history." },
  { id: "DEM-004", category: "Demographic", name: "Governorate Announcement Verification", description: "Check local rumors against official statements from the respective governorate's media office." },
  { id: "DEM-005", category: "Demographic", name: "Community Leader Source Verification", description: "Confirm statements attributed to religious or community leaders directly with their offices." },
  { id: "DEM-006", category: "Demographic", name: "Refugee Statistic Fact-Check", description: "Debunk exaggerated claims about refugee populations using UNHCR and government data." },
  { id: "DEM-007", category: "Demographic", name: "Urban Planning Rumor Debunk", description: "Verify claims about neighborhood demolitions or relocations with the Ministry of Housing." },
  { id: "DEM-008", category: "Demographic", name: "Education Policy Clarification", description: "Address rumors about changes to the Thanaweya Amma system via Ministry of Education channels." },
  { id: "DEM-009", category: "Demographic", name: "Subsidy Removal Fear-Mongering Check", description: "Verify claims about the cancellation of bread or fuel subsidies with Ministry of Supply statements." },
  { id: "DEM-010", category: "Demographic", name: "Cultural Heritage Distortion Correction", description: "Counter false narratives regarding Ancient Egyptian or Islamic heritage with expert archaeological consensus." },
  { id: "DEM-011", category: "Demographic", name: "Youth Morality Panic Analysis", description: "Contextualize viral outrage over youth behavior by comparing it to historical generational complaints." },
  { id: "DEM-012", category: "Demographic", name: "Labor Strike Rumor Verification", description: "Check reports of mass strikes or factory closures with the Ministry of Manpower or relevant syndicates." },
  { id: "DEM-013", category: "Demographic", name: "Agricultural Crisis Fact-Check", description: "Debunk claims of widespread crop failures using Ministry of Agriculture and Land Reclamation data." },
  { id: "DEM-014", category: "Demographic", name: "Water Scarcity Rumor Assessment", description: "Address panics related to the Nile water share with official Ministry of Water Resources statements." },
  { id: "DEM-015", category: "Demographic", name: "Foreign Investment Misinformation Check", description: "Verify rumors about the sale of state assets to foreign entities with Cabinet announcements." },
  { id: "DEM-016", category: "Demographic", name: "Currency Devaluation Panic Containment", description: "Counter unfounded rumors about sudden extreme exchange rate shifts using Central Bank data." },
  { id: "DEM-017", category: "Demographic", name: "Tax Law Change Verification", description: "Clarify new tax regulations to counter misinformation spreading among small business owners." },
  { id: "DEM-018", category: "Demographic", name: "Pension Scheme Rumor Debunk", description: "Address fears regarding the reduction or cancellation of pensions with the National Authority for Social Insurance." },
  { id: "DEM-019", category: "Demographic", name: "Women's Rights Legislation Clarification", description: "Provide accurate summaries of new personal status laws to counter alarmist interpretations." },
  { id: "DEM-020", category: "Demographic", name: "Crime Rate Exaggeration Check", description: "Counter viral claims of unprecedented crime waves using official Ministry of Interior statistics." },
  { id: "DEM-021", category: "Demographic", name: "Kidnapping Rumor Verification", description: "Investigate viral stories of child kidnappings, which often turn out to be false alarms or custody disputes." },
  { id: "DEM-022", category: "Demographic", name: "Traffic Fine Misinformation Debunk", description: "Clarify new traffic laws and fine structures to counter exaggerated rumors." },
  { id: "DEM-023", category: "Demographic", name: "Public Transport Fare Panic Assessment", description: "Verify rumors of sudden massive increases in metro or bus fares." },
  { id: "DEM-024", category: "Demographic", name: "Utility Bill Rumor Verification", description: "Address claims of unjustified doubling of electricity or water bills." },
  { id: "DEM-025", category: "Demographic", name: "Real Estate Bubble Panic Containment", description: "Provide expert economic analysis to counter rumors of an imminent collapse of the housing market." },
  { id: "DEM-026", category: "Demographic", name: "Tourism Incident Fact-Check", description: "Verify reports of incidents affecting tourists with the Ministry of Tourism and Antiquities." },
  { id: "DEM-027", category: "Demographic", name: "Expatriate Remittance Rumor Debunk", description: "Address false claims regarding government confiscation of remittances from Egyptians abroad." },
  { id: "DEM-028", category: "Demographic", name: "Draft/Conscription Policy Clarification", description: "Verify rumors about changes to mandatory military service regulations." },
  { id: "DEM-029", category: "Demographic", name: "Election Fraud Rumor Assessment", description: "Investigate claims of electoral irregularities using reports from official monitoring bodies." },
  { id: "DEM-030", category: "Demographic", name: "Political Prisoner Statistic Verification", description: "Cross-reference claims regarding prisoner numbers with recognized human rights organizations and government data." },
  { id: "DEM-031", category: "Demographic", name: "Border Security Incident Fact-Check", description: "Verify rumors of border clashes or infiltrations with official Armed Forces spokespersons." },
  { id: "DEM-032", category: "Demographic", name: "Smuggling Ring Rumor Debunk", description: "Address exaggerated claims about the smuggling of essential goods." },
  { id: "DEM-033", category: "Demographic", name: "Black Market Commodity Price Verification", description: "Monitor and report actual market prices to counter rumors causing panic buying." },
  { id: "DEM-034", category: "Demographic", name: "Supply Chain Disruption Assessment", description: "Verify claims that certain essential medications or foods will completely disappear from the market." },
  { id: "DEM-035", category: "Demographic", name: "Environmental Disaster Rumor Check", description: "Debunk false predictions of devastating earthquakes or tsunamis hitting Egypt." },
  { id: "DEM-036", category: "Demographic", name: "Pollution Level Exaggeration Debunk", description: "Verify claims of toxic air clouds or chemical spills with the Ministry of Environment." },
  { id: "DEM-037", category: "Demographic", name: "Animal Culling Rumor Verification", description: "Investigate reports of mass culling of stray animals by municipal authorities." },
  { id: "DEM-038", category: "Demographic", name: "Sports Match-Fixing Rumor Assessment", description: "Address viral claims of corruption in major local football matches." },
  { id: "DEM-039", category: "Demographic", name: "Celebrity Death Hoax Debunking", description: "Verify rumors regarding the death or severe illness of prominent Egyptian figures." },
  { id: "DEM-040", category: "Demographic", name: "Scandal Video Authenticity Check", description: "Investigate the origins of videos claiming to show moral failings of public figures." },
  { id: "DEM-041", category: "Demographic", name: "Charity Scam Exposure", description: "Identify fraudulent fundraising campaigns exploiting public sympathy for specific local causes." },
  { id: "DEM-042", category: "Demographic", name: "Scholarship/Visa Fraud Identification", description: "Debunk fake offers of free visas or scholarships targeting Egyptian youth." },
  { id: "DEM-043", category: "Demographic", name: "Lottery/Prize Scam Verification", description: "Expose fraudulent text messages claiming the recipient has won a large prize from a local telecom." }
];
