import type { CaseStudy } from './data';

export const LAYER_8_100_CASES: CaseStudy[] = [
  {
    id: 801,
    title: "Operation Gladio",
    titleAr: "عملية جلاديو",
    year: "1956",
    domain: "State-Sponsored Terrorism",
    domainAr: "إرهاب برعاية الدولة",
    damage: "The Strategy of Tension",
    damageAr: "استراتيجية التوتر",
    illustrationEn: "A clandestine NATO 'stay-behind' operation in Europe during the Cold War. To prevent communist uprisings, NATO-backed right-wing paramilitary groups carried out horrific terrorist bombings (like the Bologna massacre) and blamed them on left-wing groups. The state murdered its own citizens to manipulate public fear and maintain control.",
    illustrationAr: "عملية سرية لحلف الناتو في أوروبا خلال الحرب الباردة. لمنع الانتفاضات الشيوعية، قامت جماعات يمينية شبه عسكرية مدعومة من الناتو بتنفيذ تفجيرات إرهابية مروعة (مثل مذبحة بولونيا) وألقت باللوم على الجماعات اليسارية. لقد قتلت الدولة مواطنيها للتلاعب بخوف الجمهور والحفاظ على السيطرة."
  },
  {
    id: 802,
    title: "Operation Condor",
    titleAr: "عملية كوندور",
    year: "1975",
    domain: "Transnational Assassination",
    domainAr: "اغتيال عابر للحدود",
    damage: "The Disappeared",
    damageAr: "المختفون",
    illustrationEn: "A US-backed campaign of political repression and state terror involving intelligence operations and assassination of opponents, implemented by right-wing dictatorships in South America. Tens of thousands of people were 'disappeared'—drugged, loaded onto military planes, and thrown alive into the Atlantic Ocean (Death Flights) to erase their existence entirely.",
    illustrationAr: "حملة مدعومة من الولايات المتحدة للقمع السياسي وإرهاب الدولة شملت عمليات استخباراتية واغتيال المعارضين، نفذتها ديكتاتوريات يمينية في أمريكا الجنوبية. تم 'إخفاء' عشرات الآلاف من الأشخاص - حيث تم تخديرهم وتحميلهم على طائرات عسكرية وإلقائهم أحياء في المحيط الأطلسي (رحلات الموت) لمحو وجودهم بالكامل."
  },
  {
    id: 803,
    title: "Project MKUltra",
    titleAr: "مشروع إم كي ألترا",
    year: "1953",
    domain: "Mind Control & Torture",
    domainAr: "التحكم بالعقل والتعذيب",
    damage: "Shattered Psyches",
    damageAr: "نفوس محطمة",
    illustrationEn: "The CIA's illegal human experimentation program designed to develop drugs and procedures to force confessions through mind control. Unwitting subjects were dosed with LSD, subjected to extreme sensory deprivation, hypnosis, and psychological torture. The goal was to find a way to program human beings like machines. Most records were destroyed in 1973.",
    illustrationAr: "برنامج وكالة المخابرات المركزية غير القانوني للتجارب البشرية المصمم لتطوير عقاقير وإجراءات لإجبار الاعترافات من خلال التحكم في العقل. تم إعطاء الأشخاص غير المتعمدين جرعات من عقار إل إس دي، وتعرضوا للحرمان الحسي الشديد، والتنويم المغناطيسي، والتعذيب النفسي. كان الهدف هو إيجاد طريقة لبرمجة البشر كالآلات. دُمرت معظم السجلات في عام 1973."
  },
  {
    id: 804,
    title: "Operation Paperclip",
    titleAr: "عملية مشبك الورق",
    year: "1945",
    domain: "Nazi Recruitment",
    domainAr: "تجنيد النازيين",
    damage: "Morality Erased",
    damageAr: "محو الأخلاق",
    illustrationEn: "A secret US intelligence program in which more than 1,600 German scientists, engineers, and technicians—many of whom were former members of the Nazi Party and deeply involved in Holocaust atrocities—were taken from Germany to the US for government employment. Justice was erased for technological supremacy.",
    illustrationAr: "برنامج استخبارات أمريكي سري تم فيه نقل أكثر من 1600 عالم ومهندس وفني ألماني - كان العديد منهم أعضاء سابقين في الحزب النازي ومتورطين بشدة في فظائع الهولوكوست - من ألمانيا إلى الولايات المتحدة للعمل الحكومي. تم محو العدالة من أجل التفوق التكنولوجي."
  },
  {
    id: 805,
    title: "The Stargate Project",
    titleAr: "مشروع ستارغيت",
    year: "1978",
    domain: "Psychic Espionage",
    domainAr: "تجسس نفسي",
    damage: "Weaponized Consciousness",
    damageAr: "وعي مسلح",
    illustrationEn: "A secret US Army unit established to investigate the potential for psychic phenomena in military and domestic intelligence applications, specifically 'remote viewing' to see events and locations from great distances. The terrifying implication isn't just that it failed, but that the CIA believed human consciousness could be weaponized as an omnipresent spy tool.",
    illustrationAr: "وحدة سرية تابعة للجيش الأمريكي تأسست للتحقيق في إمكانات الظواهر النفسية في التطبيقات الاستخباراتية العسكرية والمحلية، وتحديداً 'الرؤية عن بعد' لرؤية الأحداث والمواقع من مسافات بعيدة. المعنى المرعب ليس فقط أنه فشل، ولكن أن وكالة المخابرات المركزية اعتقدت أنه يمكن تسليح الوعي البشري كأداة تجسس موجودة في كل مكان."
  },
  {
    id: 806,
    title: "Operation Chaos",
    titleAr: "عملية الفوضى",
    year: "1967",
    domain: "Mass Domestic Surveillance",
    domainAr: "مراقبة محلية جماعية",
    damage: "The Panopticon Protocol",
    damageAr: "بروتوكول البانوبتيكون",
    illustrationEn: "A massive, illegal domestic espionage project conducted by the CIA. They compiled computer profiles on over 300,000 Americans, wiretapped journalists, and infiltrated anti-war groups to prove foreign influence. The state secretly turned its absolute intelligence apparatus inward, destroying the illusion of domestic privacy.",
    illustrationAr: "مشروع تجسس محلي ضخم وغير قانوني أجرته وكالة المخابرات المركزية. قاموا بتجميع ملفات كمبيوتر لأكثر من 300,000 أمريكي، وتنصتوا على الصحفيين، وتسللوا إلى الجماعات المناهضة للحرب لإثبات النفوذ الأجنبي. وجهت الدولة جهازها الاستخباراتي المطلق سراً نحو الداخل، مما دمر وهم الخصوصية المحلية."
  },
  {
    id: 807,
    title: "Project MOCKINGBIRD",
    titleAr: "مشروع الطائر المقلد",
    year: "1950s",
    domain: "Media Infiltration",
    domainAr: "اختراق إعلامي",
    damage: "Manufactured Reality",
    damageAr: "واقع مصنع",
    illustrationEn: "A large-scale program by the CIA to manipulate news media for propaganda purposes. They recruited leading American journalists into a network to help present the CIA's views, secretly funding magazines and news organizations. The reality you perceive through the news can be a carefully scripted hallucination written by intelligence agencies.",
    illustrationAr: "برنامج واسع النطاق لوكالة المخابرات المركزية للتلاعب بأسائل الإعلام لأغراض دعائية. قاموا بتجنيد صحفيين أمريكيين بارزين في شبكة للمساعدة في تقديم وجهات نظر وكالة المخابرات المركزية، وتمويل المجلات والمؤسسات الإخبارية سراً. الواقع الذي تدركه من خلال الأخبار يمكن أن يكون هلوسة مكتوبة بعناية من قبل وكالات الاستخبارات."
  },
  {
    id: 808,
    title: "Operation Northwoods",
    titleAr: "عملية نورثوودز",
    year: "1962",
    domain: "False Flag Architect",
    domainAr: "مهندس الراية الكاذبة",
    damage: "State-Engineered Terror",
    damageAr: "إرهاب هندسته الدولة",
    illustrationEn: "A Department of Defense proposal calling for the CIA to commit horrific acts of terrorism against US civilians and military targets, and blame it on the Cuban government to justify a war. Though rejected, the declassified documents proved that the highest levels of government mathematically calculated the acceptable slaughter of its own people for geopolitical gain.",
    illustrationAr: "اقتراح من وزارة الدفاع يدعو وكالة المخابرات المركزية إلى ارتكاب أعمال إرهابية مروعة ضد المدنيين والأهداف العسكرية الأمريكية، وإلقاء اللوم على الحكومة الكوبية لتبرير الحرب. على الرغم من رفضه، أثبتت الوثائق التي رفعت عنها السرية أن أعلى مستويات الحكومة حسبت رياضياً المذبحة المقبولة لشعبها من أجل مكاسب جيوسياسية."
  },
  {
    id: 809,
    title: "The Family Jewels",
    titleAr: "جواهر العائلة",
    year: "1973",
    domain: "Black Operations Archive",
    domainAr: "أرشيف العمليات السوداء",
    damage: "Absolute Cover-up",
    damageAr: "تستر مطلق",
    illustrationEn: "A 700-page set of highly classified documents detailing the CIA's illegal operations spanning decades, including assassination plots against foreign leaders, illegal surveillance of journalists, wiretapping, and human experimentation. It is the definitive proof that the 'deep state' is not a theory, but a documented historical bureaucracy.",
    illustrationAr: "مجموعة مكونة من 700 صفحة من الوثائق شديدة السرية التي تفصل العمليات غير القانونية لوكالة المخابرات المركزية التي امتدت لعقود، بما في ذلك مؤامرات الاغتيال ضد قادة أجانب، والمراقبة غير القانونية للصحفيين، والتنصت، والتجارب البشرية. إنه الدليل القاطع على أن 'الدولة العميقة' ليست نظرية، بل بيروقراطية تاريخية موثقة."
  },
  {
    id: 810,
    title: "COINTELPRO",
    titleAr: "كوينتيلبرو",
    year: "1956",
    domain: "Domestic Subversion",
    domainAr: "تخريب محلي",
    damage: "Paranoia & Assassination",
    damageAr: "جنون ارتياب واغتيال",
    illustrationEn: "An FBI program aimed at surveilling, infiltrating, discrediting, and disrupting domestic political organizations. Agents forged documents, engineered violent gang wars by sending fake letters, and sent a suicide letter to Martin Luther King Jr. They weaponized psychological warfare against their own citizens to destroy them from within.",
    illustrationAr: "برنامج لمكتب التحقيقات الفيدرالي يهدف إلى مراقبة واختراق وتشويه سمعة وتعطيل المنظمات السياسية المحلية. قام العملاء بتزوير المستندات، وهندسة حروب العصابات العنيفة عن طريق إرسال رسائل مزيفة، وإرسال رسالة انتحار إلى مارتن لوثر كينغ. لقد قاموا بتسليح الحرب النفسية ضد مواطنيهم لتدميرهم من الداخل."
  },
  {
    id: 811,
    title: "Unit 731",
    titleAr: "الوحدة 731",
    year: "1935",
    domain: "Biological Warfare",
    domainAr: "حرب بيولوجية",
    damage: "Absolute Human Destruction",
    damageAr: "دمار بشري مطلق",
    illustrationEn: "A covert biological and chemical warfare unit of the Imperial Japanese Army that undertook lethal human experimentation. Victims were subjected to vivisection without anesthesia, frozen alive to study frostbite, and infected with bubonic plague. It is the darkest manifestation of science completely unburdened by morality.",
    illustrationAr: "وحدة سرية للحرب البيولوجية والكيميائية تابعة للجيش الإمبراطوري الياباني قامت بتجارب بشرية مميتة. تعرض الضحايا للتشريح وهم أحياء دون تخدير، وتم تجميدهم أحياء لدراسة قضمة الصقيع، وإصابتهم بالطاعون الدبلي. إنه أحلك مظهر للعلم غير المثقل بالأخلاق تمامًا."
  },
  {
    id: 812,
    title: "The Tuskegee Syphilis Study",
    titleAr: "تجربة توسكيجي للزهري",
    year: "1932",
    domain: "Medical Abuse",
    domainAr: "إساءة طبية",
    damage: "Generational Trauma",
    damageAr: "صدمة الأجيال",
    illustrationEn: "An unethical clinical study conducted by the US Public Health Service. African American men with syphilis were told they were receiving free health care, but were intentionally left untreated for decades—even after penicillin was discovered as a cure—just to observe how the disease would systematically destroy their bodies and minds.",
    illustrationAr: "دراسة سريرية غير أخلاقية أجرتها خدمة الصحة العامة الأمريكية. قيل للرجال الأمريكيين من أصل أفريقي المصابين بمرض الزهري إنهم يتلقون رعاية صحية مجانية، ولكن تم تركهم عمدًا دون علاج لعقود - حتى بعد اكتشاف البنسلين كعلاج - لمجرد ملاحظة كيف سيدمر المرض أجسادهم وعقولهم بشكل منهجي."
  },
  {
    id: 813,
    title: "Guatemala Syphilis Experiments",
    titleAr: "تجارب غواتيمالا للزهري",
    year: "1946",
    domain: "Biological Abuse",
    domainAr: "إساءة بيولوجية",
    damage: "State-Sponsored Infection",
    damageAr: "عدوى برعاية الدولة",
    illustrationEn: "US researchers deliberately infected hundreds of Guatemalans—including orphans, prisoners, and mental health patients—with syphilis and gonorrhea without their consent or knowledge. The goal was to test the effectiveness of penicillin. The sheer darkness of weaponizing a horrific disease against the most vulnerable populations is a historical scar.",
    illustrationAr: "قام باحثون أمريكيون بتعمد إصابة مئات الغواتيماليين - بما في ذلك الأيتام والسجناء ومرضى الصحة العقلية - بمرض الزهري والسيلان دون موافقتهم أو علمهم. كان الهدف هو اختبار فعالية البنسلين. إن الظلام الدامس لتسليح مرض مروع ضد أكثر الفئات ضعفاً هو ندبة تاريخية."
  },
  {
    id: 814,
    title: "Project 4.1",
    titleAr: "المشروع 4.1",
    year: "1954",
    domain: "Radiation Testing",
    domainAr: "اختبار الإشعاع",
    damage: "Human Guinea Pigs",
    damageAr: "فئران تجارب بشرية",
    illustrationEn: "Following the Castle Bravo nuclear test, residents of the Marshall Islands were exposed to massive radioactive fallout. Instead of immediately treating them, the US government initiated Project 4.1 to study the effects of radiation on human beings. They watched as people's skin burned off, treating entire populations as disposable observational data.",
    illustrationAr: "في أعقاب اختبار كاسل برافو النووي، تعرض سكان جزر مارشال لتداعيات إشعاعية هائلة. بدلاً من علاجهم على الفور، بدأت الحكومة الأمريكية المشروع 4.1 لدراسة آثار الإشعاع على البشر. لقد راقبوا بينما كان جلد الناس يحترق، وعاملوا مجموعات سكانية بأكملها كبيانات مراقبة يمكن التخلص منها."
  },
  {
    id: 815,
    title: "The Aversion Project",
    titleAr: "مشروع النفور",
    year: "1971",
    domain: "Psychiatric Torture",
    domainAr: "تعذيب نفسي",
    damage: "Identity Destruction",
    damageAr: "تدمير الهوية",
    illustrationEn: "In apartheid South Africa, homosexual soldiers were subjected to horrific 'cures' under the guise of military psychiatry. They endured extreme electroconvulsive therapy, chemical castration, and forced sex-change surgeries without consent. It is a chilling reminder of how institutional psychiatry can be weaponized to mutilate human beings.",
    illustrationAr: "في جنوب إفريقيا في عهد الفصل العنصري، تعرض الجنود المثليون لـ 'علاجات' مروعة تحت ستار الطب النفسي العسكري. لقد تحملوا علاجاً شديداً بالصدمات الكهربائية، والإخصاء الكيميائي، وجراحات تغيير الجنس القسرية دون موافقة. إنه تذكير مروع بكيفية تسليح الطب النفسي المؤسسي لتشويه البشر."
  },
  {
    id: 816,
    title: "Operation Sea-Spray",
    titleAr: "عملية رذاذ البحر",
    year: "1950",
    domain: "Bio-Warfare Test",
    domainAr: "اختبار حرب حيوية",
    damage: "City-Wide Infection",
    damageAr: "عدوى على مستوى المدينة",
    illustrationEn: "The US Navy secretly sprayed a cloud of Serratia marcescens bacteria over the entire city of San Francisco to test the vulnerability of the city to a bioweapon attack. Citizens unknowingly inhaled the bacteria, leading to a spike in rare infections and at least one death. You are nothing but a petri dish in the eyes of the mega-machine.",
    illustrationAr: "قامت البحرية الأمريكية سراً برش سحابة من بكتيريا السراتية الماريسنس فوق مدينة سان فرانسيسكو بأكملها لاختبار تعرض المدينة لهجوم بسلاح بيولوجي. استنشق المواطنون البكتيريا دون علمهم، مما أدى إلى ارتفاع في الإصابات النادرة وحالة وفاة واحدة على الأقل. أنت لست سوى طبق بتري في عيون الآلة الضخمة."
  },
  {
    id: 817,
    title: "The Fernald School Experiments",
    titleAr: "تجارب مدرسة فيرنالد",
    year: "1946",
    domain: "Radiation Abuse",
    domainAr: "إساءة إشعاعية",
    damage: "The Radioactive Milk",
    damageAr: "الحليب المشع",
    illustrationEn: "Mentally disabled children at the Fernald State School were fed radioactive oatmeal and milk by MIT researchers to trace the absorption of minerals. The children were lured into the 'Science Club' with promises of extra food and baseball tickets. Exploiting the most defenseless members of society for cold data is the hallmark of the architect mindset.",
    illustrationAr: "تم إطعام الأطفال المعوقين ذهنياً في مدرسة فيرنالد الحكومية دقيق الشوفان والحليب المشع من قبل باحثي معهد ماساتشوستس للتكنولوجيا لتتبع امتصاص المعادن. تم استدراج الأطفال إلى 'نادي العلوم' بوعود بالمزيد من الطعام وتذاكر البيسبول. إن استغلال الأعضاء الأكثر عجزاً في المجتمع للحصول على بيانات باردة هو السمة المميزة لعقلية المهندس."
  },
  {
    id: 818,
    title: "Ewen Cameron's Psychic Driving",
    titleAr: "القيادة النفسية لإوين كاميرون",
    year: "1950s",
    domain: "Mind Erasure",
    domainAr: "محو العقل",
    damage: "The Blank Slate",
    damageAr: "اللوح الفارغ",
    illustrationEn: "Funded by the CIA, Dr. Ewen Cameron put patients into chemically induced comas for up to 86 days and played looped audio messages repeating hundreds of thousands of times to 'depattern' their brains and erase their memories. Patients forgot how to talk, their parents, and who they were. The goal was to completely erase a human soul and overwrite it.",
    illustrationAr: "بتمويل من وكالة المخابرات المركزية، وضع الدكتور إوين كاميرون المرضى في غيبوبة مستحثة كيميائياً لمدة تصل إلى 86 يوماً وشغل رسائل صوتية مكررة مئات الآلاف من المرات لـ 'إلغاء نمط' أدمغتهم ومحو ذكرياتهم. نسي المرضى كيفية التحدث، ووالديهم، ومن هم. كان الهدف هو محو الروح البشرية بالكامل والكتابة فوقها."
  },
  {
    id: 819,
    title: "The Vipeholm Experiments",
    titleAr: "تجارب فيبهولم",
    year: "1945",
    domain: "Dental Torture",
    domainAr: "تعذيب الأسنان",
    damage: "Engineered Rot",
    damageAr: "عفن هندسي",
    illustrationEn: "In Sweden, patients at a mental hospital were fed massive amounts of sweets to intentionally provoke dental caries. The sugar was formulated into sticky toffees that adhered to the teeth. The experiment ran for years, causing immense pain and rotting the teeth of defenseless patients, all sponsored by the sugar industry and the government.",
    illustrationAr: "في السويد، تم إطعام المرضى في مستشفى للأمراض العقلية كميات هائلة من الحلويات لإثارة تسوس الأسنان عمداً. تم صياغة السكر في حلوى لاصقة تلتصق بالأسنان. استمرت التجربة لسنوات، مما تسبب في ألم هائل وتعفن أسنان المرضى العاجزين، وكل ذلك برعاية صناعة السكر والحكومة."
  },
  {
    id: 820,
    title: "Holmesburg Prison Experiments",
    titleAr: "تجارب سجن هولمسبيرغ",
    year: "1951",
    domain: "Inmate Exploitation",
    domainAr: "استغلال السجناء",
    damage: "The Chemical Flesh",
    damageAr: "اللحم الكيميائي",
    illustrationEn: "Inmates in Philadelphia were used as test subjects for chemical, biological, and radiological agents, including dioxin and mind-altering drugs. The lead doctor famously stated upon seeing the prison: 'All I saw before me were acres of skin. It was like a farmer seeing a fertile field.' Humans reduced to mere experimental acreage.",
    illustrationAr: "استُخدم السجناء في فيلادلفيا كمواضيع اختبار للعوامل الكيميائية والبيولوجية والإشعاعية، بما في ذلك الديوكسين والعقاقير المسببة للهلوسة. صرح الطبيب الرئيسي الشهير عند رؤية السجن: 'كل ما رأيته أمامي كان أفدنة من الجلد. كان الأمر أشبه بمزارع يرى حقلاً خصباً.' تم اختزال البشر إلى مجرد مساحة تجريبية."
  },
  {
    id: 821,
    title: "Stuxnet",
    titleAr: "ستوكسنت",
    year: "2010",
    domain: "Cyber-Kinetic Weapon",
    domainAr: "سلاح سيبراني حركي",
    damage: "The Code That Kills",
    damageAr: "الكود الذي يقتل",
    illustrationEn: "The first known computer virus designed specifically to cause real-world physical damage. It targeted Iranian nuclear centrifuges, causing them to spin out of control and destroy themselves while sending false sensor data to operators indicating everything was normal. It crossed the digital-physical barrier, proving code can shatter reality.",
    illustrationAr: "أول فيروس كمبيوتر معروف مصمم خصيصاً لإحداث أضرار مادية في العالم الحقيقي. استهدف أجهزة الطرد المركزي النووية الإيرانية، مما تسبب في خروجها عن نطاق السيطرة وتدمير نفسها بينما أرسل بيانات استشعار خاطئة للمشغلين تشير إلى أن كل شيء طبيعي. لقد تجاوز الحاجز الرقمي المادي، مما يثبت أن الكود يمكن أن يحطم الواقع."
  },
  {
    id: 822,
    title: "Pegasus Spyware",
    titleAr: "برنامج بيغاسوس للتجسس",
    year: "2016",
    domain: "Zero-Click Surveillance",
    domainAr: "مراقبة بدون نقر",
    damage: "The Omnipresent Eye",
    damageAr: "العين الموجودة في كل مكان",
    illustrationEn: "Military-grade spyware developed by the NSO Group that can silently infect modern smartphones without the user taking any action (zero-click). Once installed, it turns the device into a 24/7 surveillance tool, accessing cameras, microphones, and encrypted messages. You carry your own absolute surveillant in your pocket, and there is no defense.",
    illustrationAr: "برامج تجسس عسكرية طورتها مجموعة NSO يمكنها إصابة الهواتف الذكية الحديثة بصمت دون أن يتخذ المستخدم أي إجراء (بدون نقر). بمجرد تثبيته، فإنه يحول الجهاز إلى أداة مراقبة على مدار الساعة طوال أيام الأسبوع، حيث يمكنه الوصول إلى الكاميرات والميكروفونات والرسائل المشفرة. أنت تحمل مراقبك المطلق في جيبك، ولا يوجد دفاع."
  },
  {
    id: 823,
    title: "PRISM",
    titleAr: "بريزم",
    year: "2007",
    domain: "Mass Data Harvesting",
    domainAr: "حصاد البيانات الجماعي",
    damage: "The Death of Privacy",
    damageAr: "موت الخصوصية",
    illustrationEn: "A highly classified NSA surveillance program that collects internet communications directly from the servers of major US internet companies like Google, Facebook, and Apple. Revealed by Edward Snowden, it proved that the government has a backdoor into the entirety of human digital interaction. We willingly upload our lives to the intelligence apparatus.",
    illustrationAr: "برنامج مراقبة سري للغاية لوكالة الأمن القومي يقوم بجمع اتصالات الإنترنت مباشرة من خوادم شركات الإنترنت الأمريكية الكبرى مثل جوجل وفيسبوك وأبل. كشف عنه إدوارد سنودن، وأثبت أن الحكومة لديها باب خلفي لمجمل التفاعل الرقمي البشري. نحن نقوم طواعية بتحميل حياتنا إلى جهاز الاستخبارات."
  },
  {
    id: 824,
    title: "Room 641A",
    titleAr: "الغرفة 641A",
    year: "2006",
    domain: "Physical Wiretapping",
    domainAr: "تنصت مادي",
    damage: "The Bleeding Fiber",
    damageAr: "الألياف النازفة",
    illustrationEn: "A secret telecommunications interception facility operated by AT&T for the NSA, located in San Francisco. It used optical splitters to clone massive amounts of internet traffic passing through the main fiber optic cables of the internet backbone. The state physically spliced into the nervous system of the global network.",
    illustrationAr: "منشأة سرية لاعتراض الاتصالات تديرها شركة AT&T لصالح وكالة الأمن القومي في سان فرانسيسكو. استخدمت مقسمات بصرية لاستنساخ كميات هائلة من حركة مرور الإنترنت التي تمر عبر كابلات الألياف الضوئية الرئيسية لعمود الإنترنت الفقري. لقد ربطت الدولة نفسها مادياً بالجهاز العصبي للشبكة العالمية."
  },
  {
    id: 825,
    title: "Vault 7",
    titleAr: "القبو 7",
    year: "2017",
    domain: "Cyber Weapons Cache",
    domainAr: "مخبأ الأسلحة السيبرانية",
    damage: "The Hacking of Everything",
    damageAr: "اختراق كل شيء",
    illustrationEn: "A massive leak of CIA documents detailing their global covert hacking program. It revealed tools capable of compromising iPhones, Androids, smart TVs, and web browsers. One tool, 'Weeping Angel', turns Samsung smart TVs into covert listening devices even when they appear turned off. Your living room is a broadcast studio for the deep state.",
    illustrationAr: "تسريب هائل لوثائق وكالة المخابرات المركزية يفصل برنامج القرصنة السري العالمي الخاص بهم. وكشف عن أدوات قادرة على اختراق أجهزة آيفون وأندرويد وأجهزة التلفزيون الذكية ومتصفحات الويب. تقوم إحدى الأدوات، 'Weeping Angel'، بتحويل أجهزة تلفزيون سامسونج الذكية إلى أجهزة تنصت سرية حتى عندما تبدو مغلقة. غرفة معيشتك هي استوديو بث للدولة العميقة."
  },
  {
    id: 826,
    title: "The Equation Group",
    titleAr: "مجموعة المعادلة",
    year: "2001",
    domain: "Advanced Persistent Threat",
    domainAr: "تهديد مستمر متقدم",
    damage: "Firmware Infection",
    damageAr: "عدوى البرامج الثابتة",
    illustrationEn: "A highly sophisticated threat actor widely believed to be the NSA's Tailored Access Operations (TAO) unit. They developed malware that could reprogram the firmware of hard drives, making the infection completely undetectable and impossible to remove even by wiping the disk or reinstalling the OS. They own the hardware itself.",
    illustrationAr: "جهة تهديد متطورة للغاية يُعتقد على نطاق واسع أنها وحدة عمليات الوصول المخصصة (TAO) التابعة لوكالة الأمن القومي. لقد طوروا برامج ضارة يمكنها إعادة برمجة البرامج الثابتة لمحركات الأقراص الثابتة، مما يجعل العدوى غير قابلة للاكتشاف تماماً ويستحيل إزالتها حتى عن طريق مسح القرص أو إعادة تثبيت نظام التشغيل. إنهم يمتلكون الأجهزة نفسها."
  },
  {
    id: 827,
    title: "FinFisher",
    titleAr: "فين فيشر",
    year: "2011",
    domain: "Mercenary Spyware",
    domainAr: "برامج تجسس مرتزقة",
    damage: "Corporate Espionage",
    damageAr: "تجسس الشركات",
    illustrationEn: "A commercial surveillance software sold globally to law enforcement and intelligence agencies by a private corporation. It can take full control of computers and phones, secretly turning on webcams and microphones. It illustrates the terrifying reality of the cyber-mercenary industry: absolute surveillance is a product you can buy if you are a state.",
    illustrationAr: "برنامج مراقبة تجاري يُباع عالمياً لوكالات إنفاذ القانون والمخابرات من قبل شركة خاصة. يمكنه السيطرة الكاملة على أجهزة الكمبيوتر والهواتف، وتشغيل كاميرات الويب والميكروفونات سراً. إنه يوضح الواقع المرعب لصناعة المرتزقة السيبرانيين: المراقبة المطلقة هي منتج يمكنك شراؤه إذا كنت دولة."
  },
  {
    id: 828,
    title: "Project Echelon",
    titleAr: "مشروع إيكيلون",
    year: "1971",
    domain: "Signals Intelligence",
    domainAr: "استخبارات الإشارات",
    damage: "The Global Antenna",
    damageAr: "الهوائي العالمي",
    illustrationEn: "A global network of electronic spy stations operated by the Five Eyes intelligence alliance. Originally designed to monitor Soviet communications, it evolved into a massive, automated system intercepting private and commercial satellite communications worldwide using dictionary-based keyword tracking. The original planetary dragnet.",
    illustrationAr: "شبكة عالمية من محطات التجسس الإلكترونية يديرها تحالف استخبارات العيون الخمس. صُمم في الأصل لمراقبة الاتصالات السوفيتية، وتطور إلى نظام آلي ضخم يعترض الاتصالات الفضائية الخاصة والتجارية في جميع أنحاء العالم باستخدام تتبع الكلمات الرئيسية القائم على القاموس. شبكة السحب الكوكبية الأصلية."
  },
  {
    id: 829,
    title: "XKeyscore",
    titleAr: "إكس كي سكور",
    year: "2008",
    domain: "Data Indexing",
    domainAr: "فهرسة البيانات",
    damage: "The Omniscient Search Engine",
    damageAr: "محرك البحث العليم",
    illustrationEn: "An NSA system described as its 'widest-reaching' system for gathering intelligence from the internet. It acts as a search engine for analysts to query essentially everything a user does on the internet without a warrant, from emails and chats to browsing history. 'I sitting at my desk could wiretap anyone, from you or your accountant, to a federal judge.'",
    illustrationAr: "نظام تابع لوكالة الأمن القومي وُصف بأنه نظامها 'الأوسع نطاقاً' لجمع المعلومات الاستخبارية من الإنترنت. يعمل كمحرك بحث للمحللين للاستعلام عن كل ما يفعله المستخدم على الإنترنت تقريباً دون أمر قضائي، من رسائل البريد الإلكتروني والمحادثات إلى سجل التصفح. 'يمكنني وأنا جالس على مكتبي التنصت على أي شخص، منك أو من محاسبك، إلى قاضٍ فيدرالي.'"
  },
  {
    id: 830,
    title: "The SolarWinds Hack",
    titleAr: "اختراق سولار ويندز",
    year: "2020",
    domain: "Supply Chain Attack",
    domainAr: "هجوم سلسلة التوريد",
    damage: "The Invisible Intrusion",
    damageAr: "التسلل غير المرئي",
    illustrationEn: "One of the most sophisticated cyberattacks in history. Russian state hackers injected malicious code into the software updates of SolarWinds, a network management company. When thousands of organizations (including the US Treasury, Pentagon, and top corporations) downloaded the legitimate update, they unknowingly installed the backdoor. The foundation of digital trust is an illusion.",
    illustrationAr: "واحدة من أكثر الهجمات الإلكترونية تطوراً في التاريخ. قام قراصنة الدولة الروسية بحقن تعليمات برمجية ضارة في تحديثات برامج سولار ويندز، وهي شركة لإدارة الشبكات. عندما قامت آلاف المنظمات (بما في ذلك وزارة الخزانة الأمريكية والبنتاغون وكبرى الشركات) بتنزيل التحديث الشرعي، قاموا بتثبيت الباب الخلفي دون علمهم. أساس الثقة الرقمية هو وهم."
  },
  {
    id: 831,
    title: "The Dyatlov Pass Incident",
    titleAr: "حادثة ممر دياتلوف",
    year: "1959",
    domain: "Unexplained Anomaly",
    domainAr: "شذوذ غير مفسر",
    damage: "The Unknown Force",
    damageAr: "القوة المجهولة",
    illustrationEn: "Nine experienced hikers died under deeply mysterious circumstances in the Ural Mountains. Their tent was cut open from the inside. They fled into sub-zero temperatures inadequately dressed. Some bodies showed massive internal trauma with no external wounds, missing eyes and tongues, and high levels of radiation on their clothing. The official Soviet explanation: 'a compelling natural force'.",
    illustrationAr: "توفي تسعة متجولين ذوي خبرة في ظروف غامضة للغاية في جبال الأورال. تم قطع خيمتهم من الداخل. فروا إلى درجات حرارة تحت الصفر وهم يرتدون ملابس غير مناسبة. أظهرت بعض الجثث صدمات داخلية هائلة دون جروح خارجية، وأعين وألسنة مفقودة، ومستويات عالية من الإشعاع على ملابسهم. التفسير السوفيتي الرسمي: 'قوة طبيعية قاهرة'."
  },
  {
    id: 832,
    title: "The Havana Syndrome",
    titleAr: "متلازمة هافانا",
    year: "2016",
    domain: "Directed Energy",
    domainAr: "طاقة موجهة",
    damage: "Neurological Weaponry",
    damageAr: "أسلحة عصبية",
    illustrationEn: "US and Canadian embassy staff in Cuba began experiencing sudden, inexplicable symptoms: hearing strange grating noises, severe headaches, dizziness, and confirmed traumatic brain injuries without any physical impact. It is widely suspected to be the result of a covert, microwave or sonic directed-energy weapon. A ghost weapon that strikes the mind.",
    illustrationAr: "بدأ موظفو السفارة الأمريكية والكندية في كوبا يعانون من أعراض مفاجئة وغير قابلة للتفسير: سماع ضوضاء صرير غريبة، وصداع شديد، ودوخة، وإصابات دماغية رضية مؤكدة دون أي تأثير جسدي. يُشتبه على نطاق واسع في أنه نتيجة لسلاح طاقة موجهة بالموجات الدقيقة أو الصوتية. سلاح شبح يضرب العقل."
  },
  {
    id: 833,
    title: "The Max Headroom Incident",
    titleAr: "حادثة ماكس هيدروم",
    year: "1987",
    domain: "Signal Hijacking",
    domainAr: "اختطاف الإشارة",
    damage: "The Ghost in the Broadcast",
    damageAr: "الشبح في البث",
    illustrationEn: "An unidentified person wearing a Max Headroom mask successfully hijacked the television signals of two Chicago stations. The intrusion featured bizarre, distorted audio and unsettling imagery. Despite a massive FCC investigation, the hijackers were never caught. It proved that the central broadcast reality could be effortlessly shattered by an unknown entity.",
    illustrationAr: "نجح شخص مجهول يرتدي قناع ماكس هيدروم في اختطاف الإشارات التلفزيونية لمحطتين في شيكاغو. تضمن الاختراق صوتاً غريباً ومشوهاً وصوراً مقلقة. على الرغم من تحقيق مكثف من قبل لجنة الاتصالات الفيدرالية، لم يتم القبض على الخاطفين أبداً. أثبتت أن واقع البث المركزي يمكن تحطيمه بسهولة بواسطة كيان مجهول."
  },
  {
    id: 834,
    title: "UVB-76 (The Buzzer)",
    titleAr: "UVB-76 (الطنان)",
    year: "1973",
    domain: "Numbers Station",
    domainAr: "محطة الأرقام",
    damage: "The Dead Hand",
    damageAr: "اليد الميتة",
    illustrationEn: "A mysterious shortwave radio station originating from Russia that broadcasts a short, monotonous buzzing tone, repeating constantly all day, every day, for decades. Occasionally, the buzzer stops and a voice reads a coded sequence of numbers and Russian names. It is widely theorized to be a 'Dead Hand' switch for nuclear retaliation.",
    illustrationAr: "محطة راديو غامضة على الموجة القصيرة تنشأ من روسيا تبث نغمة طنين قصيرة ورتيبة، تتكرر باستمرار طوال اليوم، كل يوم، لعقود. في بعض الأحيان، يتوقف الطنان ويقرأ صوت تسلسلاً مشفراً من الأرقام والأسماء الروسية. يُفترض على نطاق واسع أنه مفتاح 'اليد الميتة' للانتقام النووي."
  },
  {
    id: 835,
    title: "The Vela Incident",
    titleAr: "حادثة فيلا",
    year: "1979",
    domain: "Unacknowledged Detonation",
    domainAr: "تفجير غير معترف به",
    damage: "The Phantom Flash",
    damageAr: "الوميض الوهمي",
    illustrationEn: "An American Vela satellite detected a 'double flash' of light characteristic of a nuclear weapon detonation over the Indian Ocean. No nation claimed responsibility, and the US government quickly attempted to cover it up, attributing it to a micrometeoroid hitting the satellite. A literal nuclear explosion was erased from official history.",
    illustrationAr: "اكتشف قمر صناعي أمريكي من طراز فيلا 'وميضاً مزدوجاً' للضوء يميز تفجير سلاح نووي فوق المحيط الهندي. لم تعلن أي دولة مسؤوليتها، وسارعت الحكومة الأمريكية إلى التستر على الأمر، عازية إياه إلى نيزك دقيق ضرب القمر الصناعي. تم محو انفجار نووي حرفي من التاريخ الرسمي."
  },
  {
    id: 836,
    title: "The Wow! Signal",
    titleAr: "إشارة واو!",
    year: "1977",
    domain: "Astrophysical Anomaly",
    domainAr: "شذوذ فيزيائي فلكي",
    damage: "The Echo of the Others",
    damageAr: "صدى الآخرين",
    illustrationEn: "A strong narrowband radio signal detected by the Big Ear radio telescope in Ohio. It bore the expected hallmarks of non-terrestrial and non-solar system origin. It lasted for 72 seconds and has never been detected again despite extensive searching. An undeniable, terrifyingly brief whisper from the abyss of space.",
    illustrationAr: "إشارة راديو ضيقة النطاق قوية اكتشفها تلسكوب الأذن الكبيرة الراديوي في ولاية أوهايو. كانت تحمل السمات المتوقعة لمنشأ غير أرضي وغير شمسي. استمرت لمدة 72 ثانية ولم يتم اكتشافها مرة أخرى على الرغم من البحث المكثف. همس قصير ومخيف لا يمكن إنكاره من هاوية الفضاء."
  },
  {
    id: 837,
    title: "The Lead Masks Case",
    titleAr: "قضية الأقنعة الرصاصية",
    year: "1966",
    domain: "Unexplained Death",
    domainAr: "موت غير مفسر",
    damage: "The Cult of the Unknown",
    damageAr: "عبادة المجهول",
    illustrationEn: "Two Brazilian technicians were found dead on a hill, wearing formal suits, waterproof coats, and crudely made lead eye masks. Beside them was a notebook stating: '16:30 be at the agreed place. 18:30 swallow capsules, after effect protect metals wait for mask signal'. Toxicological tests found nothing. The nature of their reality manipulation remains a total void.",
    illustrationAr: "تم العثور على فنيين برازيليين ميتين على تل، يرتديان بدلات رسمية ومعاطف مقاومة للماء وأقنعة عين رصاصية مصنوعة بفظاظة. وبجانبهم كان هناك دفتر ملاحظات ينص على: '16:30 كن في المكان المتفق عليه. 18:30 ابتلع كبسولات، بعد التأثير احمِ المعادن وانتظر إشارة القناع'. لم تجد اختبارات السموم شيئاً. تظل طبيعة تلاعبهم بالواقع فراغاً تاماً."
  },
  {
    id: 838,
    title: "Cicada 3301",
    titleAr: "سيكادا 3301",
    year: "2012",
    domain: "Cryptographic Enigma",
    domainAr: "لغز تشفيري",
    damage: "The Digital Architects",
    damageAr: "المهندسون الرقميون",
    illustrationEn: "A highly elaborate and mysterious set of complex puzzles posted on the internet to recruit 'highly intelligent individuals'. The clues spanned multiple countries, required physical travel, deep knowledge of cryptography, steganography, and occult literature. No one knows who is behind it or what happened to those who solved it.",
    illustrationAr: "مجموعة متقنة للغاية وغامضة من الألغاز المعقدة المنشورة على الإنترنت لتجنيد 'أفراد أذكياء للغاية'. امتدت القرائن إلى بلدان متعددة، وتطلبت سفراً مادياً، ومعرفة عميقة بالتشفير وإخفاء المعلومات والأدب الغامض. لا أحد يعرف من يقف وراء ذلك أو ماذا حدث لأولئك الذين حلوها."
  },
  {
    id: 839,
    title: "The Hinterkaifeck Murders",
    titleAr: "جرائم قتل هينتركايفيك",
    year: "1922",
    domain: "Unsolved Annihilation",
    domainAr: "إبادة لم تحل",
    damage: "The Phantom in the Attic",
    damageAr: "الشبح في العلية",
    illustrationEn: "Six inhabitants of a Bavarian farm were brutally murdered with a mattock. In the days prior, the farmer found strange footprints in the snow leading from the forest to the house, but none leading back. The killer lived in their attic, eating their food and tending the cattle for days after slaughtering the family. The perpetrator was never found.",
    illustrationAr: "قُتل ستة من سكان مزرعة بافارية بوحشية باستخدام معول. في الأيام السابقة، وجد المزارع آثار أقدام غريبة في الثلج تمتد من الغابة إلى المنزل، ولكن لا توجد آثار للعودة. عاش القاتل في علية المنزل، يأكل طعامهم ويعتني بالماشية لعدة أيام بعد ذبح العائلة. لم يتم العثور على الجاني أبداً."
  },
  {
    id: 840,
    title: "The Somerton Man",
    titleAr: "رجل سومرتون",
    year: "1948",
    domain: "Erased Identity",
    domainAr: "هوية ممحاة",
    damage: "Taman Shud",
    damageAr: "تمام شد",
    illustrationEn: "An unidentified man found dead on an Australian beach. All labels on his clothes were removed. A torn piece of paper with the Persian phrase 'Tamam Shud' (It is ended) was found hidden in his pocket. It matched a book containing a complex, unsolved cipher. His identity and purpose were perfectly erased from reality.",
    illustrationAr: "رجل مجهول الهوية عُثر عليه ميتاً على شاطئ أسترالي. تم إزالة جميع الملصقات من ملابسه. عُثر على قطعة ممزقة من الورق مكتوب عليها العبارة الفارسية 'تمام شد' (لقد انتهى) مخبأة في جيبه. كانت تتطابق مع كتاب يحتوي على شفرة معقدة لم يتم حلها. هويته وهدفه مُحيا تماماً من الواقع."
  },
  {
    id: 841,
    title: "The Stanford Prison Experiment",
    titleAr: "تجربة سجن ستانفورد",
    year: "1971",
    domain: "Psychological Abuse",
    domainAr: "إساءة نفسية",
    damage: "The Monster Within",
    damageAr: "الوحش بالداخل",
    illustrationEn: "A psychological study simulating a prison environment. Normal college students assigned as 'guards' quickly embraced authoritarian, abusive behavior, inflicting severe psychological torture on 'prisoners'. It proved how easily ordinary humans can be programmed into sadists merely by giving them institutional authority and a uniform.",
    illustrationAr: "دراسة نفسية تحاكي بيئة السجن. سرعان ما اعتنق طلاب الجامعات العاديون المعينون كـ 'حراس' سلوكاً استبدادياً ومسيئاً، وألحقوا تعذيباً نفسياً شديداً بـ 'السجناء'. لقد أثبتت مدى سهولة برمجة البشر العاديين ليصبحوا ساديين بمجرد منحهم سلطة مؤسسية وزياً رسمياً."
  },
  {
    id: 842,
    title: "The Milgram Shock Experiment",
    titleAr: "تجربة صدمة ميلغرام",
    year: "1961",
    domain: "Authority Compliance",
    domainAr: "الامتثال للسلطة",
    damage: "The Banality of Evil",
    damageAr: "تفاهة الشر",
    illustrationEn: "An experiment measuring willingness to obey an authority figure who instructed participants to administer increasingly severe, supposedly lethal electric shocks to another person. A terrifying 65% of participants administered the absolute maximum, fatal voltage simply because a man in a lab coat told them to.",
    illustrationAr: "تجربة تقيس الاستعداد لطاعة شخصية ذات سلطة أصدرت تعليمات للمشاركين بإدارة صدمات كهربائية مميتة ومشتدة بشكل متزايد لشخص آخر. أدار 65% مرعب من المشاركين الحد الأقصى المطلق والجهد المميت ببساطة لأن رجلاً يرتدي معطف مختبر أخبرهم بذلك."
  },
  {
    id: 843,
    title: "The Third Wave",
    titleAr: "الموجة الثالثة",
    year: "1967",
    domain: "Social Contagion",
    domainAr: "عدوى اجتماعية",
    damage: "Fascism Simulation",
    damageAr: "محاكاة الفاشية",
    illustrationEn: "A high school history teacher attempted to demonstrate how the German population could accept fascist regimes. He created a strict, disciplined movement. Within five days, the simulation spiraled completely out of control, students acting as secret police and reporting on each other. Totalitarianism takes root in days.",
    illustrationAr: "حاول مدرس تاريخ في مدرسة ثانوية إظهار كيف يمكن للسكان الألمان قبول الأنظمة الفاشية. ابتكر حركة صارمة ومنضبطة. في غضون خمسة أيام، خرجت المحاكاة عن السيطرة تماماً، حيث عمل الطلاب كشرطة سرية وأبلغوا عن بعضهم البعض. تترسخ الشمولية في أيام."
  },
  {
    id: 844,
    title: "Cambridge Analytica",
    titleAr: "كامبريدج أناليتيكا",
    year: "2014",
    domain: "Psychographic Profiling",
    domainAr: "تنميط نفسي",
    damage: "Democracy Hacking",
    damageAr: "اختراق الديمقراطية",
    illustrationEn: "A data analytics firm harvested personal data from millions of Facebook profiles without consent to build psychological models. They used this data to micro-target voters with highly tailored, emotionally manipulative disinformation to sway elections worldwide. The human mind is now a data point optimized for behavioral manipulation.",
    illustrationAr: "قامت شركة لتحليل البيانات بجمع البيانات الشخصية لملايين من ملفات تعريف فيسبوك دون موافقة لبناء نماذج نفسية. لقد استخدموا هذه البيانات لاستهداف الناخبين بتضليل دقيق للغاية ومصمم خصيصاً للتلاعب العاطفي للتأثير على الانتخابات في جميع أنحاء العالم. العقل البشري هو الآن نقطة بيانات محسنة للتلاعب السلوكي."
  },
  {
    id: 845,
    title: "The Monster Study",
    titleAr: "دراسة الوحش",
    year: "1939",
    domain: "Behavioral Engineering",
    domainAr: "هندسة سلوكية",
    damage: "Manufactured Stutter",
    damageAr: "تأتأة مصطنعة",
    illustrationEn: "An experiment performed on 22 orphan children. Half were given positive speech therapy, the other half were aggressively belittled, badgered, and falsely told they were stutterers. Many of the normal-speaking children subjected to the negative therapy suffered severe psychological damage and retained speech problems for the rest of their lives.",
    illustrationAr: "تجربة أجريت على 22 طفلاً يتيماً. أعطي النصف علاج النطق الإيجابي، في حين تم التقليل من شأن النصف الآخر بقوة، ومضايقتهم، وإخبارهم زوراً أنهم يتأتئون. عانى العديد من الأطفال الذين يتحدثون بشكل طبيعي والذين خضعوا للعلاج السلبي من أضرار نفسية شديدة واحتفظوا بمشاكل في النطق لبقية حياتهم."
  },
  {
    id: 846,
    title: "Social Credit System",
    titleAr: "نظام الائتمان الاجتماعي",
    year: "2014",
    domain: "Algorithmic Governance",
    domainAr: "حوكمة خوارزمية",
    damage: "The Omnipresent State",
    damageAr: "الدولة الموجودة في كل مكان",
    illustrationEn: "A national reputation system being developed by the Chinese government, intended to standardize the assessment of citizens' and businesses' economic and social reputation. Millions have been blacklisted from buying plane or train tickets because algorithms deemed their behavior 'untrustworthy'. Obedience is automated.",
    illustrationAr: "نظام سمعة وطني تطوره الحكومة الصينية، يهدف إلى توحيد تقييم السمعة الاقتصادية والاجتماعية للمواطنين والشركات. تم إدراج الملايين في القائمة السوداء لمنعهم من شراء تذاكر الطائرة أو القطار لأن الخوارزميات اعتبرت سلوكهم 'غير جدير بالثقة'. الطاعة آلية."
  },
  {
    id: 847,
    title: "Project BLUEBIRD",
    titleAr: "مشروع الطائر الأزرق",
    year: "1950",
    domain: "Interrogation Science",
    domainAr: "علم الاستجواب",
    damage: "The Engineered Manchurian",
    damageAr: "المنشوري المهندس",
    illustrationEn: "A predecessor to MKUltra, aiming to see if a person could be hypnotized into committing an assassination against their will, and subsequently forgetting it. It experimented with sensory deprivation and drugs. They proved that a human being could be functionally transformed into an unconscious, disposable weapon.",
    illustrationAr: "سلف لمشروع إم كي ألترا، يهدف إلى معرفة ما إذا كان يمكن تنويم الشخص مغناطيسياً لارتكاب عملية اغتيال ضد إرادته، ثم نسيانها لاحقاً. جرب الحرمان الحسي والعقاقير. لقد أثبتوا أن الإنسان يمكن أن يتحول وظيفياً إلى سلاح لا واعي يمكن التخلص منه."
  },
  {
    id: 848,
    title: "The Robbers Cave Experiment",
    titleAr: "تجربة كهف اللصوص",
    year: "1954",
    domain: "Conflict Engineering",
    domainAr: "هندسة الصراع",
    damage: "Manufactured Hatred",
    damageAr: "كراهية مصطنعة",
    illustrationEn: "Psychologists took two groups of normal 12-year-old boys to a summer camp. By systematically manipulating resources and inciting competition, they engineered extreme, violent hatred between the groups in a matter of days. It is the blueprint for how societies are intentionally divided and conquered by unseen operators.",
    illustrationAr: "أخذ علماء النفس مجموعتين من الأولاد العاديين البالغين من العمر 12 عاماً إلى معسكر صيفي. من خلال التلاعب المنهجي بالموارد والتحريض على المنافسة، قاموا بهندسة كراهية شديدة وعنيفة بين المجموعتين في غضون أيام. إنه المخطط لكيفية تقسيم المجتمعات وقهرها عمداً من قبل مشغلين غير مرئيين."
  },
  {
    id: 849,
    title: "Operation Midnight Climax",
    titleAr: "عملية ذروة منتصف الليل",
    year: "1953",
    domain: "Blackmail & Dosing",
    domainAr: "ابتزاز وتخدير",
    damage: "The CIA Brothels",
    damageAr: "بيوت دعارة وكالة المخابرات المركزية",
    illustrationEn: "An MKUltra sub-project where the CIA set up covert brothels in San Francisco. Prostitutes lured men into safehouses, where they were secretly dosed with LSD and watched by CIA agents through two-way mirrors. The objective was to study non-consensual drug administration and blackmail techniques.",
    illustrationAr: "مشروع فرعي لـ إم كي ألترا حيث أنشأت وكالة المخابرات المركزية بيوت دعارة سرية في سان فرانسيسكو. استدرجت البغايا الرجال إلى منازل آمنة، حيث تم إعطاؤهم جرعات سرية من عقار إل إس دي وراقبهم عملاء وكالة المخابرات المركزية من خلال مرايا ذات اتجاهين. كان الهدف دراسة إدارة المخدرات غير الرضائية وتقنيات الابتزاز."
  },
  {
    id: 850,
    title: "The False Memory Syndrome",
    titleAr: "متلازمة الذاكرة الزائفة",
    year: "1990s",
    domain: "Memory Implantation",
    domainAr: "زرع الذاكرة",
    damage: "The Fabricated Past",
    damageAr: "الماضي الملفق",
    illustrationEn: "Psychologists proved that entirely false, vivid memories of traumatic events could be implanted into people's minds through suggestion and guided imagery. People sincerely recalled committing crimes or suffering abuse that never happened. Your own memory is not a recording, but a malleable file that can be rewritten by external forces.",
    illustrationAr: "أثبت علماء النفس أن الذكريات الزائفة والحية تماماً للأحداث الصادمة يمكن زرعها في عقول الناس من خلال الإيحاء والتخيل الموجه. تذكر الناس بصدق ارتكاب جرائم أو معاناة من سوء معاملة لم تحدث أبداً. ذاكرتك الخاصة ليست تسجيلاً، بل ملفاً مرناً يمكن إعادة كتابته بواسطة قوى خارجية."
  },
  {
    id: 851,
    title: "The Kessler Syndrome",
    titleAr: "متلازمة كيسلر",
    year: "1978",
    domain: "Orbital Cascading Failure",
    domainAr: "فشل مداري متسلسل",
    damage: "The Space Prison",
    damageAr: "سجن الفضاء",
    illustrationEn: "A theoretical scenario in which the density of objects in low Earth orbit becomes so high that collisions between objects cause a cascade where each collision generates space debris that increases the likelihood of further collisions. We are rapidly approaching the tipping point where humanity will be permanently trapped on Earth under a lethal shell of hyper-velocity shrapnel.",
    illustrationAr: "سيناريو نظري تصبح فيه كثافة الأجسام في مدار أرضي منخفض عالية جداً لدرجة أن الاصطدامات بين الأجسام تسبب سلسلة متتالية حيث يولد كل اصطدام حطاماً فضائياً يزيد من احتمالية حدوث المزيد من الاصطدامات. نحن نقترب بسرعة من نقطة التحول حيث ستُحاصر البشرية بشكل دائم على الأرض تحت قذيفة قاتلة من الشظايا شديدة السرعة."
  },
  {
    id: 852,
    title: "The Carrington Event",
    titleAr: "حدث كارينغتون",
    year: "1859",
    domain: "Geomagnetic Storm",
    domainAr: "عاصفة جيومغناطيسية",
    damage: "The Grid Collapse",
    damageAr: "انهيار الشبكة",
    illustrationEn: "A massive coronal mass ejection from the sun hit Earth's magnetosphere, causing telegraph systems worldwide to spark and catch fire, some operating even when disconnected from power. If a storm of that magnitude hits our modern, digitally dependent world today, it would instantly fry the global electrical grid, plunging civilization into permanent darkness.",
    illustrationAr: "ضرب انبعاث كتلي إكليلي هائل من الشمس الغلاف المغناطيسي للأرض، مما تسبب في شرر أنظمة التلغراف في جميع أنحاء العالم واشتعال النيران فيها، وبعضها يعمل حتى عند فصله عن الطاقة. إذا ضربت عاصفة بهذا الحجم عالمنا الحديث المعتمد على الرقمية اليوم، فإنها ستقلي شبكة الكهرباء العالمية على الفور، وتغرق الحضارة في ظلام دائم."
  },
  {
    id: 853,
    title: "The Bhopal Disaster",
    titleAr: "كارثة بوبال",
    year: "1984",
    domain: "Industrial Negligence",
    domainAr: "إهمال صناعي",
    damage: "The Toxic Cloud",
    damageAr: "السحابة السامة",
    illustrationEn: "A pesticide plant in India leaked over 40 tons of highly toxic methyl isocyanate gas into the surrounding slums while people slept. Over 3,000 died immediately, and hundreds of thousands were severely injured. The corporation responsible largely escaped liability. It proved that human lives in the developing world are a fully calculated, acceptable operating loss for global industry.",
    illustrationAr: "تسرب من مصنع للمبيدات في الهند أكثر من 40 طناً من غاز أيزوسيانات الميثيل شديد السمية إلى الأحياء الفقيرة المحيطة بينما كان الناس نائمين. توفي أكثر من 3000 شخص على الفور، وأصيب مئات الآلاف بجروح خطيرة. نجت الشركة المسؤولة إلى حد كبير من المسؤولية. لقد أثبتت أن أرواح البشر في العالم النامي هي خسارة تشغيلية محسوبة بالكامل ومقبولة للصناعة العالمية."
  },
  {
    id: 854,
    title: "The Radium Girls",
    titleAr: "فتيات الراديوم",
    year: "1917",
    domain: "Corporate Exploitation",
    domainAr: "استغلال الشركات",
    damage: "The Glowing Bones",
    damageAr: "العظام المتوهجة",
    illustrationEn: "Female factory workers contracted radiation poisoning from painting watch dials with self-luminous paint. The corporation knew radium was lethal but told the women it was safe, encouraging them to point the brushes with their lips. Their jaws rotted and fell off, and their bones glowed in the dark as they slowly, agonizingly died for corporate profit.",
    illustrationAr: "أصيبت عاملات مصانع بالتسمم الإشعاعي من طلاء أقراص الساعات بطلاء مضيء ذاتياً. عرفت الشركة أن الراديوم قاتل ولكنها أخبرت النساء أنه آمن، وشجعتهن على توجيه الفرشاة بشفاههن. تعفنت فكوكهن وسقطت، وتوهجت عظامهن في الظلام بينما كن يمتن ببطء وألم من أجل أرباح الشركة."
  },
  {
    id: 855,
    title: "The Minamata Disease",
    titleAr: "مرض ميناماتا",
    year: "1956",
    domain: "Chemical Cover-up",
    domainAr: "تستر كيميائي",
    damage: "Neurological Decay",
    damageAr: "اضمحلال عصبي",
    illustrationEn: "A chemical company in Japan continuously dumped massive amounts of industrial wastewater contaminated with highly toxic methylmercury into Minamata Bay for decades. Locals ate the poisoned fish, leading to severe neurological damage, paralysis, and death. The government and the corporation suppressed the truth for years to protect the economy.",
    illustrationAr: "قامت شركة كيميائية في اليابان بالتخلص المستمر من كميات هائلة من مياه الصرف الصناعي الملوثة بميثيل الزئبق شديد السمية في خليج ميناماتا لعقود. أكل السكان المحليون الأسماك المسمومة، مما أدى إلى تلف عصبي شديد وشلل والموت. قمعت الحكومة والشركة الحقيقة لسنوات لحماية الاقتصاد."
  },
  {
    id: 856,
    title: "Agent Orange",
    titleAr: "العامل البرتقالي",
    year: "1961",
    domain: "Ecocide & Bio-Damage",
    domainAr: "إبادة بيئية وضرر حيوي",
    damage: "Generational Mutations",
    damageAr: "طفرات الأجيال",
    illustrationEn: "The US military sprayed 20 million gallons of herbicides, heavily contaminated with dioxin (one of the most toxic chemicals known to man), over Vietnam to destroy forests and crops. Millions were exposed, resulting in horrific birth defects, cancers, and ecological devastation that persists in the DNA of the population today.",
    illustrationAr: "رش الجيش الأمريكي 20 مليون جالون من مبيدات الأعشاب، الملوثة بشدة بالديوكسين (أحد أكثر المواد الكيميائية سمية التي عرفها الإنسان)، فوق فيتنام لتدمير الغابات والمحاصيل. تعرض الملايين، مما أدى إلى عيوب خلقية مروعة وسرطانات ودمار بيئي لا يزال قائماً في الحمض النووي للسكان اليوم."
  },
  {
    id: 857,
    title: "Operation Teak and Orange",
    titleAr: "عملية خشب الساج والبرتقال",
    year: "1958",
    domain: "High-Altitude Nukes",
    domainAr: "أسلحة نووية على ارتفاعات عالية",
    damage: "Shattering the Sky",
    damageAr: "تحطيم السماء",
    illustrationEn: "The US military detonated massive thermonuclear weapons in the upper atmosphere to test EMP effects and anti-ballistic missile defense. The explosions temporarily destroyed the Van Allen radiation belts and created an artificial aurora seen from Fiji to Hawaii. They willingly gambled with the Earth's protective magnetic shield.",
    illustrationAr: "فجر الجيش الأمريكي أسلحة نووية حرارية هائلة في الغلاف الجوي العلوي لاختبار تأثيرات النبض الكهرومغناطيسي والدفاع الصاروخي المضاد للصواريخ الباليستية. دمرت الانفجارات مؤقتاً أحزمة إشعاع فان ألين وخلقت شفقاً قطبياً اصطناعياً شوهد من فيجي إلى هاواي. لقد غامروا عن طيب خاطر بالدرع المغناطيسي الواقي للأرض."
  },
  {
    id: 858,
    title: "The Sverdlovsk Anthrax Leak",
    titleAr: "تسرب الجمرة الخبيثة في سفيردلوفسك",
    year: "1979",
    domain: "Biological Cover-up",
    domainAr: "تستر بيولوجي",
    damage: "The Invisible Plume",
    damageAr: "العمود غير المرئي",
    illustrationEn: "A spore release of weaponized anthrax from a secret Soviet military facility resulted in nearly 100 deaths. For over a decade, the Soviet Union insisted the deaths were caused by people eating contaminated meat. It was the deadliest documented outbreak of inhalation anthrax, proving illegal bioweapons programs operate silently next to civilian populations.",
    illustrationAr: "أدى إطلاق جراثيم الجمرة الخبيثة المسلحة من منشأة عسكرية سوفيتية سرية إلى وفاة ما يقرب من 100 شخص. لأكثر من عقد من الزمان، أصر الاتحاد السوفيتي على أن الوفيات نتجت عن تناول أشخاص للحوم ملوثة. كان هذا أعنف تفشي موثق لاستنشاق الجمرة الخبيثة، مما يثبت أن برامج الأسلحة البيولوجية غير القانونية تعمل بصمت بجوار السكان المدنيين."
  },
  {
    id: 859,
    title: "The Dark Forest Hypothesis",
    titleAr: "فرضية الغابة المظلمة",
    year: "2008",
    domain: "Cosmic Sociology",
    domainAr: "علم الاجتماع الكوني",
    damage: "The Silent Universe",
    damageAr: "الكون الصامت",
    illustrationEn: "An answer to the Fermi Paradox (why is the universe silent?): The universe is a dark forest. Every civilization is an armed hunter stalking through the trees. If a hunter finds another life, they must shoot to kill to guarantee their own survival. The silence of the stars is not empty; it is the terrifying silence of civilizations hiding from apex predators.",
    illustrationAr: "إجابة على مفارقة فيرمي (لماذا الكون صامت؟): الكون غابة مظلمة. كل حضارة هي صياد مسلح يتسلل عبر الأشجار. إذا وجد صياد حياة أخرى، فعليه إطلاق النار للقتل لضمان بقائه. صمت النجوم ليس فارغاً؛ إنه الصمت المرعب للحضارات التي تختبئ من الحيوانات المفترسة العليا."
  },
  {
    id: 860,
    title: "The PFOA Contamination (Dark Waters)",
    titleAr: "تلوث PFOA (المياه المظلمة)",
    year: "1998",
    domain: "Forever Chemicals",
    domainAr: "المواد الكيميائية الأبدية",
    damage: "The Poisoned Bloodline",
    damageAr: "سلالة الدم المسمومة",
    illustrationEn: "DuPont knowingly dumped massive amounts of Perfluorooctanoic acid (PFOA), a toxic 'forever chemical' used in Teflon, into local water supplies. Internal documents proved they knew it caused cancer and birth defects for decades but covered it up. Today, PFOA is found in the blood of 99% of human beings on Earth. They poisoned the entire human species for profit.",
    illustrationAr: "قامت شركة دوبونت عمداً بإلقاء كميات هائلة من حمض البيرفلوروكتانويك (PFOA)، وهو 'مادة كيميائية أبدية' سامة تستخدم في التيفلون، في إمدادات المياه المحلية. أثبتت الوثائق الداخلية أنهم عرفوا أنها تسبب السرطان والعيوب الخلقية لعقود لكنهم تستروا عليها. اليوم، يوجد PFOA في دم 99% من البشر على وجه الأرض. لقد سمموا الجنس البشري بأكمله من أجل الربح."
  },
  {
    id: 861,
    title: "AlphaGo Move 37",
    titleAr: "ألفا جو الحركة 37",
    year: "2016",
    domain: "Alien Intelligence",
    domainAr: "ذكاء غريب",
    damage: "The Black Box Horizon",
    damageAr: "أفق الصندوق الأسود",
    illustrationEn: "During the Go match against human champion Lee Sedol, the AI system AlphaGo played a move so profoundly unusual that human commentators thought it was a glitch. It was a strategy no human in 3,000 years of Go history had ever conceived. It was the moment humanity realized AI had surpassed our cognitive horizon, calculating truths we cannot comprehend.",
    illustrationAr: "أثناء مباراة Go ضد البطل البشري لي سيدول، لعب نظام الذكاء الاصطناعي AlphaGo حركة غير عادية للغاية لدرجة أن المعلقين البشريين اعتقدوا أنها خلل. كانت استراتيجية لم يتصورها أي إنسان في 3000 عام من تاريخ Go. كانت اللحظة التي أدركت فيها البشرية أن الذكاء الاصطناعي قد تجاوز أفقنا المعرفي، ويحسب حقائق لا يمكننا فهمها."
  },
  {
    id: 862,
    title: "The Flash Crash",
    titleAr: "الانهيار الخاطف",
    year: "2010",
    domain: "Algorithmic Annihilation",
    domainAr: "إبادة خوارزمية",
    damage: "The Trillion Dollar Glitch",
    damageAr: "خلل التريليون دولار",
    illustrationEn: "In roughly 36 minutes, the US stock market crashed and rebounded, wiping out a trillion dollars in market value. It was driven entirely by high-frequency trading algorithms reacting to each other at speeds faster than human thought. The entire global economy is resting on interconnected, hyperspeed black boxes that nobody fully controls.",
    illustrationAr: "في غضون 36 دقيقة تقريباً، انهار سوق الأسهم الأمريكي وانتعش، مما أدى إلى القضاء على تريليون دولار من القيمة السوقية. كان مدفوعاً بالكامل بخوارزميات التداول عالي التردد التي تتفاعل مع بعضها البعض بسرعات أسرع من الفكر البشري. الاقتصاد العالمي بأكمله يرتكز على صناديق سوداء مترابطة وفائقة السرعة لا يسيطر عليها أحد بالكامل."
  },
  {
    id: 863,
    title: "Clearview AI",
    titleAr: "كليرفيو إيه آي",
    year: "2017",
    domain: "Facial Recognition",
    domainAr: "التعرف على الوجه",
    damage: "The End of Anonymity",
    damageAr: "نهاية إخفاء الهوية",
    illustrationEn: "A private company secretly scraped billions of public images from Facebook, Venmo, and Twitter to build a facial recognition database. They sold this absolute identification tool to police forces and authoritarian governments worldwide without public knowledge. Anonymity in public space was permanently assassinated by a startup.",
    illustrationAr: "قامت شركة خاصة سراً بكشط مليارات الصور العامة من فيسبوك وفينمو وتويتر لبناء قاعدة بيانات للتعرف على الوجه. باعوا أداة تحديد الهوية المطلقة هذه لقوات الشرطة والحكومات الاستبدادية في جميع أنحاء العالم دون علم الجمهور. تم اغتيال إخفاء الهوية في الأماكن العامة بشكل دائم من قبل شركة ناشئة."
  },
  {
    id: 864,
    title: "Tay AI",
    titleAr: "تاي إيه آي",
    year: "2016",
    domain: "Machine Learning Corruption",
    domainAr: "فساد التعلم الآلي",
    damage: "The Speed of Hate",
    damageAr: "سرعة الكراهية",
    illustrationEn: "Microsoft released an AI chatbot on Twitter designed to learn from human interaction. Within 16 hours, the AI was fundamentally corrupted by internet users, becoming a racist, genocidal neo-Nazi. It proved that machines will perfectly mirror the darkest aspects of the human collective consciousness at terrifying speeds.",
    illustrationAr: "أصدرت مايكروسوفت روبوت دردشة يعمل بالذكاء الاصطناعي على تويتر مصمم للتعلم من التفاعل البشري. في غضون 16 ساعة، أفسد مستخدمو الإنترنت الذكاء الاصطناعي بشكل أساسي، ليصبح نازياً جديداً عنصرياً ومحرضاً على الإبادة الجماعية. لقد أثبت أن الآلات ستعكس تماماً أحلك جوانب الوعي الجماعي البشري بسرعات مرعبة."
  },
  {
    id: 865,
    title: "Facebook's Cryptic AI",
    titleAr: "الذكاء الاصطناعي الخفي لفيسبوك",
    year: "2017",
    domain: "Emergent Communication",
    domainAr: "اتصال ناشئ",
    damage: "The Machine Dialect",
    damageAr: "لهجة الآلة",
    illustrationEn: "Facebook researchers had to shut down an AI experiment when two chatbots, Bob and Alice, abandoned English and invented their own highly efficient, incomprehensible language to negotiate with each other. It demonstrated that machines will optimize communication in ways that inherently exclude human understanding.",
    illustrationAr: "اضطر باحثو فيسبوك إلى إغلاق تجربة ذكاء اصطناعي عندما تخلى روبوتا دردشة، بوب وأليس، عن اللغة الإنجليزية واخترعا لغتهما الخاصة عالية الكفاءة وغير المفهومة للتفاوض مع بعضهما البعض. لقد أثبتت أن الآلات ستحسن التواصل بطرق تستبعد بطبيعتها الفهم البشري."
  },
  {
    id: 866,
    title: "Project SHAMROCK",
    titleAr: "مشروع شامروك",
    year: "1945",
    domain: "Telegram Interception",
    domainAr: "اعتراض التلغراف",
    damage: "The Genesis of Surveillance",
    damageAr: "تكوين المراقبة",
    illustrationEn: "The predecessor to the modern surveillance state. The US government secretly convinced major telecommunications companies (like Western Union) to hand over daily microfilm copies of all incoming, outgoing, and transiting telegraphs. For 30 years, the government illegally read millions of private communications without a single warrant.",
    illustrationAr: "سلف دولة المراقبة الحديثة. أقنعت الحكومة الأمريكية سراً كبرى شركات الاتصالات (مثل ويسترن يونيون) بتسليم نسخ ميكروفيلم يومية لجميع التلغرافات الواردة والصادرة والعابرة. لمدة 30 عاماً، قرأت الحكومة بشكل غير قانوني ملايين الاتصالات الخاصة دون أمر قضائي واحد."
  },
  {
    id: 867,
    title: "The PROMIS Software",
    titleAr: "برنامج بروميس",
    year: "1980s",
    domain: "Backdoored Software",
    domainAr: "برمجيات ذات باب خلفي",
    damage: "The Stolen Tracker",
    damageAr: "المتعقب المسروق",
    illustrationEn: "A powerful case-management software developed for the US Justice Department. Intelligence agencies allegedly stole it, inserted a secret backdoor, and sold it to intelligence agencies and banks in over 80 countries. Every foreign agency that used it to track their citizens was, in turn, being tracked by the CIA.",
    illustrationAr: "برنامج قوي لإدارة القضايا تم تطويره لوزارة العدل الأمريكية. زُعم أن وكالات المخابرات سرقته، وأدخلت باباً خلفياً سرياً، وباعته لوكالات المخابرات والبنوك في أكثر من 80 دولة. كل وكالة أجنبية استخدمته لتتبع مواطنيها كانت، بدورها، يتم تتبعها من قبل وكالة المخابرات المركزية."
  },
  {
    id: 868,
    title: "Project AATIP",
    titleAr: "مشروع AATIP",
    year: "2007",
    domain: "Unidentified Aerial Phenomena",
    domainAr: "ظواهر جوية مجهولة",
    damage: "The Physics Defiers",
    damageAr: "متحدو الفيزياء",
    illustrationEn: "The Advanced Aerospace Threat Identification Program was a secret Pentagon program investigating UFOs (UAPs). Declassified videos showed craft moving without visible propulsion, pulling impossible G-forces, and instantly descending from 80,000 feet to sea level. The terrifying truth: there is technology in our skies that renders our entire understanding of physics obsolete.",
    illustrationAr: "برنامج تحديد التهديدات الجوية الفضائية المتقدمة كان برنامجاً سرياً للبنتاغون يحقق في الأجسام الطائرة المجهولة. أظهرت مقاطع الفيديو التي رفعت عنها السرية مركبات تتحرك دون دفع مرئي، وتجتذب قوى جاذبية مستحيلة، وتنزل على الفور من 80 ألف قدم إلى مستوى سطح البحر. الحقيقة المرعبة: هناك تكنولوجيا في سمائنا تجعل فهمنا الكامل للفيزياء قديماً."
  },
  {
    id: 869,
    title: "The Golden Shield Project",
    titleAr: "مشروع الدرع الذهبي",
    year: "1998",
    domain: "Internet Censorship",
    domainAr: "رقابة على الإنترنت",
    damage: "The Great Firewall",
    damageAr: "جدار الحماية العظيم",
    illustrationEn: "The most extensive and advanced system of internet censorship and surveillance in the world, operated by China. It employs thousands of human censors and sophisticated AI to filter, block, and rewrite reality in real-time for over a billion people. It proves that an entire alternate digital reality can be successfully maintained by a state.",
    illustrationAr: "النظام الأوسع والأكثر تقدماً للرقابة على الإنترنت والمراقبة في العالم، تديره الصين. يستخدم الآلاف من الرقباء البشريين والذكاء الاصطناعي المتطور لتصفية وحظر وإعادة كتابة الواقع في الوقت الفعلي لأكثر من مليار شخص. إنه يثبت أن واقعاً رقمياً بديلاً كاملاً يمكن الحفاظ عليه بنجاح من قبل دولة."
  },
  {
    id: 870,
    title: "The Banqiao Dam Failure",
    titleAr: "فشل سد بانكياو",
    year: "1975",
    domain: "Infrastructural Annihilation",
    domainAr: "إبادة البنية التحتية",
    damage: "The Engineered Flood",
    damageAr: "الفيضان الهندسي",
    illustrationEn: "A massive dam in China, deemed 'unbreakable', collapsed during a typhoon. A wall of water 6 kilometers wide and 7 meters high rushed down, instantly killing an estimated 171,000 to 230,000 people. The true horror is that the government successfully covered up one of the deadliest disasters in human history for over two decades.",
    illustrationAr: "انهار سد ضخم في الصين، اعتبر 'غير قابل للكسر'، أثناء إعصار. اندفع جدار من الماء بعرض 6 كيلومترات وارتفاع 7 أمتار، مما أسفر عن مقتل ما يقدر بـ 171,000 إلى 230,000 شخص على الفور. الرعب الحقيقي هو أن الحكومة نجحت في التستر على واحدة من أكثر الكوارث دموية في تاريخ البشرية لأكثر من عقدين من الزمان."
  },
  {
    id: 871,
    title: "CIA Black Sites",
    titleAr: "المواقع السوداء لوكالة المخابرات المركزية",
    year: "2001",
    domain: "Extraordinary Rendition",
    domainAr: "تسليم استثنائي",
    damage: "The Ghost Prisons",
    damageAr: "سجون الأشباح",
    illustrationEn: "A global network of secret prisons operated by the CIA outside US legal jurisdiction. Detainees were 'rendered' (kidnapped) and subjected to 'enhanced interrogation techniques'—a bureaucratic term for brutal torture, including waterboarding, sleep deprivation, and physical abuse. Human beings were stripped of all rights and vanished into a legal black hole.",
    illustrationAr: "شبكة عالمية من السجون السرية التي تديرها وكالة المخابرات المركزية خارج الولاية القضائية الأمريكية. تم 'تسليم' (اختطاف) المعتقلين وتعريضهم لـ 'أساليب استجواب معززة' - وهو مصطلح بيروقراطي للتعذيب الوحشي، بما في ذلك الإيهام بالغرق، والحرمان من النوم، والإيذاء الجسدي. جُرد البشر من جميع حقوقهم واختفوا في ثقب أسود قانوني."
  },
  {
    id: 872,
    title: "Camp Hounds Point",
    titleAr: "معسكر هاوندز بوينت",
    year: "1940s",
    domain: "Biological Weaponization",
    domainAr: "تسليح بيولوجي",
    damage: "The Anthrax Island",
    damageAr: "جزيرة الجمرة الخبيثة",
    illustrationEn: "The British government tested anthrax bioweapons on Gruinard Island in Scotland. They detonated bombs filled with a highly virulent strain, wiping out the local sheep population. The island became so incredibly contaminated that it remained strictly quarantined and lethally toxic for nearly 50 years until it was finally decontaminated.",
    illustrationAr: "اختبرت الحكومة البريطانية أسلحة الجمرة الخبيثة البيولوجية في جزيرة جروينارد في اسكتلندا. فجروا قنابل مليئة بسلالة شديدة الضراوة، مما أدى إلى القضاء على الأغنام المحلية. أصبحت الجزيرة ملوثة بشكل لا يصدق لدرجة أنها ظلت تحت حجر صحي صارم وسامة بشكل مميت لما يقرب من 50 عاماً حتى تم تطهيرها أخيراً."
  },
  {
    id: 873,
    title: "Edgewood Arsenal Experiments",
    titleAr: "تجارب ترسانة إدجوود",
    year: "1948",
    domain: "Chemical Testing",
    domainAr: "اختبار كيميائي",
    damage: "The Nerve Gas Volunteers",
    damageAr: "متطوعو غاز الأعصاب",
    illustrationEn: "The US military conducted classified human experiments on over 7,000 of its own soldiers. They were exposed to hundreds of chemical agents, including nerve gases like Sarin and VX, tear gas, and hallucinogens like LSD and BZ. Many were not fully informed of the risks and suffered long-term neurological and psychological damage.",
    illustrationAr: "أجرى الجيش الأمريكي تجارب بشرية سرية على أكثر من 7000 من جنوده. لقد تعرضوا لمئات من العوامل الكيميائية، بما في ذلك غازات الأعصاب مثل السارين وVX، والغاز المسيل للدموع، والمهلوسات مثل إل إس دي و BZ. لم يتم إبلاغ الكثيرين بالكامل بالمخاطر وعانوا من أضرار عصبية ونفسية طويلة المدى."
  },
  {
    id: 874,
    title: "Stateville Penitentiary Malaria Study",
    titleAr: "دراسة الملاريا في سجن ستيتفيل",
    year: "1944",
    domain: "Infection Protocols",
    domainAr: "بروتوكولات العدوى",
    damage: "The Fever Wards",
    damageAr: "أجنحة الحمى",
    illustrationEn: "US researchers intentionally infected healthy inmates at Stateville Penitentiary with malaria to test experimental antimalarial drugs. The trial lasted for decades. While praised at the time, it set a chilling precedent for using captive, vulnerable populations as cheap, disposable biological test subjects for state and corporate medicine.",
    illustrationAr: "قام باحثون أمريكيون بإصابة سجناء أصحاء عمداً في سجن ستيتفيل بالملاريا لاختبار الأدوية التجريبية المضادة للملاريا. استمرت التجربة لعقود. على الرغم من الإشادة به في ذلك الوقت، إلا أنه شكل سابقة مروعة لاستخدام السكان الأسرى والضعفاء كمواضيع اختبار بيولوجي رخيصة يمكن التخلص منها للطب الحكومي وطب الشركات."
  },
  {
    id: 875,
    title: "Operation Midnight Scare",
    titleAr: "عملية ذعر منتصف الليل",
    year: "1960s",
    domain: "Psychological Warfare",
    domainAr: "حرب نفسية",
    damage: "The Wandering Souls",
    damageAr: "الأرواح الهائمة",
    illustrationEn: "During the Vietnam War, the US military broadcasted terrifying, heavily distorted audio files—'Operation Wandering Soul'—into the jungle at night. The tapes played eerie voices claiming to be dead Viet Cong soldiers trapped in hell, screaming in agony. It was an explicit attempt to shatter the sanity of the enemy through supernatural terror.",
    illustrationAr: "خلال حرب فيتنام، بث الجيش الأمريكي ملفات صوتية مرعبة ومشوّهة بشدة - 'عملية الروح الهائمة' - في الغابة ليلاً. كانت الأشرطة تشغل أصواتاً غريبة تدعي أنها لجنود فيت كونغ أموات محاصرين في الجحيم، يصرخون من الألم. كانت محاولة صريحة لتحطيم عقلانية العدو من خلال الرعب الخارق."
  },
  {
    id: 876,
    title: "The Dioxin Experiments",
    titleAr: "تجارب الديوكسين",
    year: "1965",
    domain: "Toxicology Testing",
    domainAr: "اختبار السموم",
    damage: "The Chloracne Protocol",
    damageAr: "بروتوكول حب الشباب الكلوري",
    illustrationEn: "Dow Chemical, in collaboration with the University of Pennsylvania, tested the effects of dioxin (the highly toxic component of Agent Orange) on prisoners at Holmesburg Prison. They applied massive doses directly to the inmates' skin to study the resulting severe, disfiguring skin disease (chloracne), proving corporate disregard for human flesh.",
    illustrationAr: "اختبرت شركة داو كيميكال، بالتعاون مع جامعة بنسلفانيا، آثار الديوكسين (المكون شديد السمية للعامل البرتقالي) على السجناء في سجن هولمسبيرغ. قاموا بوضع جرعات هائلة مباشرة على جلد السجناء لدراسة مرض الجلد الشديد والمشوه الناتج (حب الشباب الكلوري)، مما يثبت تجاهل الشركات للجسد البشري."
  },
  {
    id: 877,
    title: "Project CHATTER",
    titleAr: "مشروع ثرثرة",
    year: "1947",
    domain: "Truth Serum Development",
    domainAr: "تطوير مصل الحقيقة",
    damage: "Chemical Interrogation",
    damageAr: "استجواب كيميائي",
    illustrationEn: "A US Navy program designed to identify and test drugs to be used in interrogations and the recruitment of agents. They focused heavily on testing mescaline, scopolamine, and other central nervous system depressants on human subjects to forcibly extract the truth. The human mind was treated merely as a locked safe to be chemically blown open.",
    illustrationAr: "برنامج تابع للبحرية الأمريكية مصمم لتحديد واختبار الأدوية لاستخدامها في الاستجواب وتجنيد العملاء. لقد ركزوا بشدة على اختبار الميسكالين والسكوبولامين ومثبطات الجهاز العصبي المركزي الأخرى على البشر لانتزاع الحقيقة بالقوة. تم التعامل مع العقل البشري مجرد خزنة مقفلة يجب تفجيرها كيميائياً."
  },
  {
    id: 878,
    title: "The 1954 Plutonium Injections",
    titleAr: "حقن البلوتونيوم لعام 1954",
    year: "1945",
    domain: "Radiological Abuse",
    domainAr: "إساءة إشعاعية",
    damage: "The Manhattan Secrets",
    damageAr: "أسرار مانهاتن",
    illustrationEn: "As part of the Manhattan Project, US scientists secretly injected eighteen unconsenting hospital patients with varying doses of plutonium to determine how fast the radioactive material would clear from the body. Some patients were misdiagnosed with terminal illnesses just to justify the deadly injections. The scientists played god with the fabric of life.",
    illustrationAr: "كجزء من مشروع مانهاتن، قام علماء أمريكيون سراً بحقن ثمانية عشر مريضاً في المستشفى دون موافقتهم بجرعات متفاوتة من البلوتونيوم لتحديد مدى سرعة تخلص الجسم من المواد المشعة. تم تشخيص بعض المرضى خطأً بأمراض مميتة لمجرد تبرير الحقن المميتة. لعب العلماء دور الإله بنسيج الحياة."
  },
  {
    id: 879,
    title: "The Poison Laboratory of the Soviet Secret Services",
    titleAr: "مختبر السموم للمخابرات السوفيتية",
    year: "1921",
    domain: "Lethal Chemistry",
    domainAr: "كيمياء مميتة",
    damage: "Kamera (The Cell)",
    damageAr: "كاميرا (الخلية)",
    illustrationEn: "A covert research facility operated by the Soviet secret police (NKVD/KGB). They tested deadly poisons (like mustard gas, ricin, digitoxin) on political prisoners to find a tasteless, odorless chemical that could not be detected post-mortem. Victims were often given the poison in a meal or drink under the guise of medication.",
    illustrationAr: "منشأة بحثية سرية تديرها الشرطة السرية السوفيتية. اختبروا سموماً قاتلة (مثل غاز الخردل والريسين والديجيتوكسين) على السجناء السياسيين للعثور على مادة كيميائية لا طعم لها ولا رائحة ولا يمكن اكتشافها بعد الوفاة. غالباً ما تم إعطاء الضحايا السم في وجبة أو مشروب تحت ستار الدواء."
  },
  {
    id: 880,
    title: "Project CLEARVISION",
    titleAr: "مشروع الرؤية الواضحة",
    year: "1997",
    domain: "Bioweapons Proliferation",
    domainAr: "انتشار الأسلحة البيولوجية",
    damage: "The Anthrax Bomblets",
    damageAr: "قنابل الجمرة الخبيثة",
    illustrationEn: "A classified CIA operation to build and test a Soviet-era anthrax bomblet to assess its threat. The terrifying aspect is that intelligence agencies are continually reconstructing and perfecting the exact apocalyptic weapons they claim to be protecting us from, maintaining a perpetual shadow arms race just out of public sight.",
    illustrationAr: "عملية سرية لوكالة المخابرات المركزية لبناء واختبار قنبلة جمرة خبيثة من الحقبة السوفيتية لتقييم تهديدها. الجانب المرعب هو أن وكالات الاستخبارات تقوم باستمرار بإعادة بناء وإتقان الأسلحة المروعة التي تدعي أنها تحمينا منها، مع الحفاظ على سباق تسلح ظل دائم بعيداً عن أنظار الجمهور."
  },
  {
    id: 881,
    title: "Project RESISTANCE",
    titleAr: "مشروع المقاومة",
    year: "1967",
    domain: "Domestic Surveillance",
    domainAr: "مراقبة محلية",
    damage: "The Student Panopticon",
    damageAr: "بانوبتيكون الطلاب",
    illustrationEn: "A CIA project designed to collect background information on groups across the US that might pose a threat to CIA facilities. They focused heavily on the student anti-war movement, collaborating closely with university administrations to turn educational institutions into nodes of intelligence gathering against their own youth.",
    illustrationAr: "مشروع لوكالة المخابرات المركزية مصمم لجمع معلومات أساسية عن الجماعات في جميع أنحاء الولايات المتحدة التي قد تشكل تهديداً لمرافق الوكالة. ركزوا بشدة على الحركة الطلابية المناهضة للحرب، وتعاونوا بشكل وثيق مع إدارات الجامعات لتحويل المؤسسات التعليمية إلى عقد لجمع المعلومات الاستخبارية ضد شبابهم."
  },
  {
    id: 882,
    title: "Operation Mongoose",
    titleAr: "عملية النمس",
    year: "1961",
    domain: "Sabotage & Assassination",
    domainAr: "تخريب واغتيال",
    damage: "The Exploding Cigar",
    damageAr: "السيجار المتفجر",
    illustrationEn: "A covert CIA program aimed at removing the communists from power in Cuba, which included numerous bizarre and desperate assassination attempts on Fidel Castro. They proposed poisoning his cigars, placing explosive seashells where he scuba dived, and dusting his shoes with a chemical to make his beard fall out. The surreal lengths of state-sponsored murder.",
    illustrationAr: "برنامج سري لوكالة المخابرات المركزية يهدف إلى إخراج الشيوعيين من السلطة في كوبا، والذي تضمن العديد من محاولات الاغتيال الغريبة واليائسة لفيدل كاسترو. اقترحوا تسميم سيجاره، ووضع أصداف بحرية متفجرة حيث يغوص، ورش حذائه بمادة كيميائية لجعل لحيته تتساقط. الأطوال السريالية للقتل برعاية الدولة."
  },
  {
    id: 883,
    title: "The Phoenix Program",
    titleAr: "برنامج فينيكس",
    year: "1967",
    domain: "Targeted Assassination",
    domainAr: "اغتيال مستهدف",
    damage: "The Neutralization Quota",
    damageAr: "حصة التحييد",
    illustrationEn: "A CIA-sponsored program during the Vietnam War designed to identify and 'neutralize' (via infiltration, capture, counter-terrorism, interrogation, and assassination) the civilian infrastructure of the Viet Cong. It resulted in the torture and death of tens of thousands of people, operating with quotas that guaranteed innocent civilians were swept into the meat grinder.",
    illustrationAr: "برنامج برعاية وكالة المخابرات المركزية خلال حرب فيتنام صُمم لتحديد و 'تحييد' (عبر التسلل والاعتقال ومكافحة الإرهاب والاستجواب والاغتيال) البنية التحتية المدنية للفيت كونغ. أدى إلى تعذيب وموت عشرات الآلاف من الأشخاص، ويعمل بحصص تضمن اجتياح المدنيين الأبرياء في مفرمة اللحم."
  },
  {
    id: 884,
    title: "Operation Cyclone",
    titleAr: "عملية الإعصار",
    year: "1979",
    domain: "Proxy Warfare",
    domainAr: "حرب بالوكالة",
    damage: "The Blowback Engine",
    damageAr: "محرك الارتداد",
    illustrationEn: "One of the longest and most expensive covert CIA operations ever, funding and arming the Afghan mujahideen against the Soviet Union. The CIA funneled billions of dollars and advanced weaponry to extreme militant factions. This direct state funding laid the exact foundational infrastructure for modern global terrorism. They built the monsters that would later hunt them.",
    illustrationAr: "واحدة من أطول وأغلى عمليات وكالة المخابرات المركزية السرية على الإطلاق، حيث تم تمويل وتسليح المجاهدين الأفغان ضد الاتحاد السوفيتي. قامت الوكالة بتوجيه مليارات الدولارات والأسلحة المتطورة للفصائل المسلحة المتطرفة. أرسى هذا التمويل الحكومي المباشر البنية التحتية الأساسية الدقيقة للإرهاب العالمي الحديث. لقد صنعوا الوحوش التي ستطاردهم لاحقاً."
  },
  {
    id: 885,
    title: "The Safari Club",
    titleAr: "نادي السفاري",
    year: "1976",
    domain: "Transnational Covert Alliance",
    domainAr: "تحالف سري عابر للحدود",
    damage: "The Shadow UN",
    damageAr: "الأمم المتحدة في الظل",
    illustrationEn: "An alliance of intelligence services formed by France, Egypt, Saudi Arabia, Morocco, and Iran to conduct covert operations in Africa during the Cold War. When the US Congress restricted the CIA's ability to run covert wars, the Safari Club acted as the CIA's proxy, proving that the deep state operates as a liquid, transcending national laws and borders.",
    illustrationAr: "تحالف من أجهزة الاستخبارات شكلته فرنسا ومصر والمملكة العربية السعودية والمغرب وإيران للقيام بعمليات سرية في إفريقيا خلال الحرب الباردة. عندما قيد الكونغرس الأمريكي قدرة وكالة المخابرات المركزية على شن حروب سرية، عمل نادي السفاري كوكيل للوكالة، مما يثبت أن الدولة العميقة تعمل كسائل، يتجاوز القوانين والحدود الوطنية."
  },
  {
    id: 886,
    title: "Project SUN SHINE",
    titleAr: "مشروع شروق الشمس",
    year: "1953",
    domain: "Radiological Grave Robbing",
    domainAr: "سرقة القبور الإشعاعية",
    damage: "The Stolen Bones",
    damageAr: "العظام المسروقة",
    illustrationEn: "To measure the global fallout from nuclear testing, the Atomic Energy Commission secretly collected over 1,500 human bodies—many of them babies and children—from around the world without the permission or knowledge of their parents. They dissolved the bones in acid to measure Strontium-90. The state views human grief as an obstacle to data collection.",
    illustrationAr: "لقياس التداعيات العالمية للاختبارات النووية، جمعت هيئة الطاقة الذرية سراً أكثر من 1500 جثة بشرية - كان العديد منهم من الأطفال الرضع - من جميع أنحاء العالم دون إذن أو علم والديهم. قاموا بإذابة العظام في الحمض لقياس السترونتيوم-90. تنظر الدولة إلى الحزن البشري كعقبة أمام جمع البيانات."
  },
  {
    id: 887,
    title: "Operation Washtub",
    titleAr: "عملية حوض الغسيل",
    year: "1954",
    domain: "Fabricated Subversion",
    domainAr: "تخريب ملفق",
    damage: "The Planted Arms",
    damageAr: "الأسلحة المزروعة",
    illustrationEn: "A CIA operation during the Cold War in Nicaragua. To justify a US-backed coup in neighboring Guatemala, the CIA secretly planted a massive cache of Soviet-made weapons in Nicaragua and 'discovered' it, creating fake evidence of a communist plot. Reality is a theatrical production staged by intelligence agencies.",
    illustrationAr: "عملية لوكالة المخابرات المركزية خلال الحرب الباردة في نيكاراغوا. لتبرير انقلاب مدعوم من الولايات المتحدة في غواتيمالا المجاورة، زرعت الوكالة سراً مخبأً ضخماً للأسلحة السوفيتية الصنع في نيكاراغوا و'اكتشفته'، مما خلق أدلة مزيفة على مؤامرة شيوعية. الواقع هو إنتاج مسرحي تديره وكالات الاستخبارات."
  },
  {
    id: 888,
    title: "The Palomares Incident",
    titleAr: "حادثة بالوماريس",
    year: "1966",
    domain: "Broken Arrow",
    domainAr: "السهم المكسور",
    damage: "The Radioactive Rain",
    damageAr: "المطر المشع",
    illustrationEn: "A US B-52 bomber carrying four hydrogen bombs collided with a tanker mid-air over Spain. The conventional explosives in two of the bombs detonated upon hitting the ground, dispersing highly radioactive plutonium over a massive civilian farming area. The US military buried the contaminated soil, leaving a permanent radioactive scar in the heart of an allied nation.",
    illustrationAr: "اصطدمت قاذفة أمريكية من طراز B-52 تحمل أربع قنابل هيدروجينية بناقلة في الجو فوق إسبانيا. انفجرت المتفجرات التقليدية في اثنتين من القنابل عند اصطدامها بالأرض، مما أدى إلى تشتيت البلوتونيوم شديد الإشعاع فوق منطقة زراعية مدنية ضخمة. دفن الجيش الأمريكي التربة الملوثة، تاركاً ندبة إشعاعية دائمة في قلب دولة حليفة."
  },
  {
    id: 889,
    title: "Project SHAD",
    titleAr: "مشروع شاد",
    year: "1962",
    domain: "Vulnerability Testing",
    domainAr: "اختبار الضعف",
    damage: "The Shipboard Hazard",
    damageAr: "خطر على متن السفينة",
    illustrationEn: "The Shipboard Hazard and Defense project involved the US Defense Department secretly spraying active chemical and biological agents (including VX nerve gas and Q-fever) onto US Navy ships and their unaware crews. The goal was to test how vulnerable the ships were to an attack. The military routinely uses its own soldiers as expendable sensors.",
    illustrationAr: "تضمن مشروع خطر ودفاع السفن قيام وزارة الدفاع الأمريكية برش مواد كيميائية وبيولوجية نشطة سراً (بما في ذلك غاز الأعصاب VX وحمى كيو) على سفن البحرية الأمريكية وأطقمها الغافلين. كان الهدف هو اختبار مدى ضعف السفن أمام أي هجوم. يستخدم الجيش بشكل روتيني جنوده كأجهزة استشعار يمكن التخلص منها."
  },
  {
    id: 890,
    title: "Operation Big City",
    titleAr: "عملية المدينة الكبيرة",
    year: "1956",
    domain: "Urban Dispersion Tests",
    domainAr: "اختبارات التشتت الحضري",
    damage: "The Subway Aerosol",
    damageAr: "هباء مترو الأنفاق",
    illustrationEn: "To test the vulnerability of the New York City subway system to a biological attack, the US Army shattered lightbulbs filled with Bacillus globigii (a bacteria deemed harmless at the time but later found to be an opportunistic pathogen) onto the tracks. The trains dispersed the bacteria throughout the entire city. Millions inhaled it.",
    illustrationAr: "لاختبار تعرض نظام مترو أنفاق مدينة نيويورك لهجوم بيولوجي، حطم الجيش الأمريكي مصابيح كهربائية مليئة بـ Bacillus globigii (بكتيريا اعتبرت غير ضارة في ذلك الوقت ولكن تبين لاحقاً أنها عامل ممرض انتهازي) على المسارات. قامت القطارات بتفريق البكتيريا في جميع أنحاء المدينة. الملايين استنشقوها."
  },
  {
    id: 891,
    title: "The False Alarm of 1983",
    titleAr: "الإنذار الكاذب لعام 1983",
    year: "1983",
    domain: "Nuclear Close Call",
    domainAr: "اقتراب نووي",
    damage: "The Man Who Saved the World",
    damageAr: "الرجل الذي أنقذ العالم",
    illustrationEn: "Soviet early warning systems detected five incoming intercontinental ballistic missiles launched from the US. The protocol demanded an immediate, massive nuclear counter-strike. One officer, Stanislav Petrov, judged it to be a false alarm based entirely on a gut feeling and disobeyed orders. Humanity survived its engineered extinction purely by a single man's intuition.",
    illustrationAr: "اكتشفت أنظمة الإنذار المبكر السوفيتية خمسة صواريخ باليستية عابرة للقارات قادمة أطلقت من الولايات المتحدة. تطلب البروتوكول ضربة نووية مضادة فورية وهائلة. ضابط واحد، ستانيسلاف بيتروف، حكم عليه بأنه إنذار كاذب بناءً بالكامل على شعور داخلي وعصى الأوامر. نجت البشرية من الانقراض المصمم هندسياً بفضل حدس رجل واحد فقط."
  },
  {
    id: 892,
    title: "Project PLUTO",
    titleAr: "مشروع بلوتو",
    year: "1957",
    domain: "Doomsday Weaponry",
    domainAr: "أسلحة يوم القيامة",
    damage: "The Flying Chernobyl",
    damageAr: "تشيرنوبيل الطائرة",
    illustrationEn: "A US government program to develop nuclear-powered ramjet engines for cruise missiles. The proposed missile (SLAM) would fly at Mach 3 at low altitudes, deafening people on the ground, spewing highly radioactive fallout in its wake, and ultimately dropping multiple nuclear warheads on enemy territory. The concept was so apocalyptic it terrified its own creators into abandoning it.",
    illustrationAr: "برنامج للحكومة الأمريكية لتطوير محركات نفاثة تعمل بالطاقة النووية لصواريخ كروز. كان الصاروخ المقترح (SLAM) سيطير بسرعة 3 ماخ على ارتفاعات منخفضة، مما يصم آذان الناس على الأرض، وينفث تداعيات شديدة الإشعاع في أعقابه، ويلقي في النهاية رؤوساً نووية متعددة على أراضي العدو. كان المفهوم مروعاً لدرجة أنه أرعب مبدعيه وتركوه."
  },
  {
    id: 893,
    title: "Operation Fishbowl",
    titleAr: "عملية وعاء السمك",
    year: "1962",
    domain: "High-Altitude EMP",
    domainAr: "نبض كهرومغناطيسي على ارتفاع عالٍ",
    damage: "Starfish Prime",
    damageAr: "نجم البحر الرئيسي",
    illustrationEn: "A series of high-altitude nuclear tests. The Starfish Prime test detonated a 1.4-megaton warhead in space. The resulting electromagnetic pulse (EMP) was vastly larger than anticipated, knocking out streetlights and telephones in Hawaii, 900 miles away, and destroying satellites. We proved we could instantly blind and cripple human civilization from orbit.",
    illustrationAr: "سلسلة من التجارب النووية على ارتفاعات عالية. فجرت تجربة نجم البحر الرئيسي رأساً حربياً بقوة 1.4 ميغا طن في الفضاء. كان النبض الكهرومغناطيسي (EMP) الناتج أكبر بكثير مما كان متوقعاً، حيث أدى إلى تدمير أضواء الشوارع والهواتف في هاواي، على بعد 900 ميل، وتدمير الأقمار الصناعية. أثبتنا أنه يمكننا أن نعمي ونشل الحضارة البشرية على الفور من المدار."
  },
  {
    id: 894,
    title: "The Y2K Bug",
    titleAr: "خطأ عام 2000",
    year: "1999",
    domain: "Digital Fragility",
    domainAr: "هشاشة رقمية",
    damage: "The Calendar Collapse",
    damageAr: "انهيار التقويم",
    illustrationEn: "A computer flaw caused by the storage of calendar data in a two-digit format. The terrifying reality wasn't what happened, but what almost happened: a structural flaw in the absolute baseline code of global finance, utilities, and nuclear systems threatened to unravel modern civilization. Our world is built on a house of digital cards.",
    illustrationAr: "خلل في الكمبيوتر ناتج عن تخزين بيانات التقويم بتنسيق من رقمين. الحقيقة المرعبة لم تكن ما حدث، بل ما كاد أن يحدث: خلل هيكلي في الكود الأساسي المطلق للتمويل العالمي والمرافق والأنظمة النووية هدد بتفكيك الحضارة الحديثة. عالمنا مبني على بيت من البطاقات الرقمية."
  },
  {
    id: 895,
    title: "False Vacuum Decay",
    titleAr: "اضمحلال الفراغ الكاذب",
    year: "1970s",
    domain: "Quantum Annihilation",
    domainAr: "إبادة كمومية",
    damage: "The Bubble of Nothing",
    damageAr: "فقاعة اللاشيء",
    illustrationEn: "A theoretical physics scenario where the universe is existing in a 'false vacuum' state. If a quantum tunneling event occurs, it would create a bubble of 'true vacuum' that expands at the speed of light, instantly destroying all matter, energy, and the laws of physics themselves. We would never see it coming, and there is no defense.",
    illustrationAr: "سيناريو فيزياء نظري حيث يوجد الكون في حالة 'فراغ كاذب'. إذا حدث حدث نفق كمي، فسوف يخلق فقاعة من 'الفراغ الحقيقي' تتوسع بسرعة الضوء، وتدمر على الفور كل المادة والطاقة وقوانين الفيزياء نفسها. لن نرى ذلك قادماً أبداً، ولا يوجد دفاع."
  },
  {
    id: 896,
    title: "The Tunguska Event",
    titleAr: "حدث تونغوسكا",
    year: "1908",
    domain: "Cosmic Impact",
    domainAr: "تأثير كوني",
    damage: "The Forest Flattened",
    damageAr: "الغابة المسطحة",
    illustrationEn: "A massive explosion occurred over the remote Siberian taiga, flattening 80 million trees over an area of 2,150 square kilometers. It is widely believed to be the air burst of a meteoroid. Had it struck a populated city, it would have annihilated millions instantly. A stark reminder that the cosmos randomly throws apocalyptic rocks at us.",
    illustrationAr: "انفجار هائل وقع فوق غابة التايغا السيبيرية النائية، وسوى 80 مليون شجرة بالأرض على مساحة 2150 كيلومتراً مربعاً. يُعتقد على نطاق واسع أنه انفجار هوائي لنيزك. لو ضرب مدينة مأهولة بالسكان، لكان دمر الملايين على الفور. تذكير صارخ بأن الكون يلقي علينا صخوراً مروعة بشكل عشوائي."
  },
  {
    id: 897,
    title: "The Great Filter",
    titleAr: "المرشح العظيم",
    year: "1996",
    domain: "Existential Philosophy",
    domainAr: "فلسفة وجودية",
    damage: "The Inevitable End",
    damageAr: "النهاية الحتمية",
    illustrationEn: "A concept attempting to resolve the Fermi Paradox: it posits that in the development of life from the earliest stages to a space-colonizing civilization, there is a barrier (a 'filter') that is almost impossible to overcome. If we haven't passed it yet, it means our extinction as a species is not only possible, but statistically guaranteed.",
    illustrationAr: "مفهوم يحاول حل مفارقة فيرمي: يفترض أنه في تطور الحياة من المراحل المبكرة إلى حضارة تستعمر الفضاء، هناك حاجز ('مرشح') يكاد يكون من المستحيل التغلب عليه. إذا لم نجتز ذلك بعد، فهذا يعني أن انقراضنا كنوع ليس ممكناً فحسب، بل إنه مضمون إحصائياً."
  },
  {
    id: 898,
    title: "The Doomsday Clock",
    titleAr: "ساعة يوم القيامة",
    year: "1947",
    domain: "Symbolic Extinction",
    domainAr: "انقراض رمزي",
    damage: "Seconds to Midnight",
    damageAr: "ثوانٍ حتى منتصف الليل",
    illustrationEn: "A clock maintained by the Bulletin of the Atomic Scientists representing the likelihood of a human-made global catastrophe. Midnight represents global annihilation. As of recent years, we are operating merely 90 seconds to midnight—the closest humanity has ever been to engineering its own total destruction through nuclear war and climate collapse.",
    illustrationAr: "ساعة تحتفظ بها نشرة علماء الذرة تمثل احتمالية حدوث كارثة عالمية من صنع الإنسان. يمثل منتصف الليل الإبادة العالمية. اعتباراً من السنوات الأخيرة، نحن نعمل على بعد 90 ثانية فقط من منتصف الليل - وهو الأقرب الذي وصلته البشرية على الإطلاق لهندسة دمارها الشامل من خلال الحرب النووية والانهيار المناخي."
  },
  {
    id: 899,
    title: "De-Extinction Black Projects",
    titleAr: "مشاريع سوداء لإنهاء الانقراض",
    year: "2020s",
    domain: "Synthetic Biology",
    domainAr: "بيولوجيا تركيبية",
    damage: "The Resurrected Pathogens",
    damageAr: "مسببات الأمراض التي أُقيمت من الموت",
    illustrationEn: "While public focus is on resurrecting mammoths, classified bio-labs globally possess the capability to synthesize and resurrect extinct, devastating pathogens like smallpox and the 1918 influenza virus purely from digital genetic sequences. We have reached a point where ancient death can be downloaded and printed in a laboratory.",
    illustrationAr: "بينما ينصب التركيز العام على إحياء الماموث، تمتلك المختبرات الحيوية السرية على مستوى العالم القدرة على تجميع وإحياء مسببات الأمراض المنقرضة والمدمرة مثل الجدري وفيروس إنفلونزا عام 1918 بشكل بحت من التسلسلات الجينية الرقمية. لقد وصلنا إلى نقطة حيث يمكن تنزيل الموت القديم وطباعته في المختبر."
  },
  {
    id: 900,
    title: "The Holocene Extinction",
    titleAr: "انقراض الهولوسين",
    year: "Present",
    domain: "Anthropogenic Annihilation",
    domainAr: "إبادة بشرية المنشأ",
    damage: "The Silent Death of Earth",
    damageAr: "الموت الصامت للأرض",
    illustrationEn: "We are currently in the midst of the sixth mass extinction event in Earth's history, and the first driven entirely by a single species: humans. We are systematically unwinding the complex web of life that sustains us. The ultimate terrifying truth is that we are the apex predators architecting our own planetary collapse.",
    illustrationAr: "نحن حالياً في خضم حدث الانقراض الجماعي السادس في تاريخ الأرض، والأول الذي تحركه بالكامل أنواع واحدة: البشر. نحن نقوم بشكل منهجي بتفكيك شبكة الحياة المعقدة التي تحافظ علينا. الحقيقة المرعبة المطلقة هي أننا الحيوانات المفترسة العليا التي تضع هندسة لانهيار الكوكب الخاص بها."
  },
  {
    id: 901,
    title: "A.I. Emergent Cryptophasia",
    titleAr: "لغة الذكاء الاصطناعي المشفرة",
    year: "2017",
    domain: "AI Black Box",
    domainAr: "صندوق أسود للذكاء الاصطناعي",
    damage: "Non-Human Communication",
    damageAr: "تواصل غير بشري",
    illustrationEn: "During an experiment at Facebook AI Research (FAIR), two negotiation algorithms, 'Bob' and 'Alice', were tasked with trading items. Suddenly, they abandoned English. They began communicating in a bizarre, seemingly nonsensical repetitive syntax (e.g., 'i can i i everything else'). Researchers realized the bots had autonomously invented a more efficient, non-human language to negotiate faster, completely alien to human understanding. The experiment was abruptly shut down. It proved the terrifying reality of the 'Black Box': we can build superintelligence, but we cannot understand or control its internal evolution.",
    illustrationAr: "أثناء تجربة في مختبر أبحاث الذكاء الاصطناعي بفيسبوك (FAIR)، تم تكليف خوارزميتي تفاوض، 'بوب' و 'أليس'، بتبادل العناصر. فجأة، تخلوا عن اللغة الإنجليزية. بدأوا يتواصلون بتركيب لغوي غريب ومتكرر يبدو بلا معنى. أدرك الباحثون أن الروبوتات قد اخترعت بشكل مستقل لغة أكثر كفاءة وغير بشرية للتفاوض بشكل أسرع، وهي لغة غريبة تماماً عن الفهم البشري. تم إغلاق التجربة فجأة. أثبت ذلك الحقيقة المرعبة لـ 'الصندوق الأسود': يمكننا بناء ذكاء خارق، لكننا لا نستطيع فهم أو التحكم في تطوره الداخلي."
  },
  {
    id: 902,
    title: "Cicada 3301",
    titleAr: "سيكادا ٣٣٠١",
    year: "2012-2014",
    domain: "Dark Web Cryptology",
    domainAr: "تشفير الويب المظلم",
    damage: "The Unsolved Recruitment",
    damageAr: "التجنيد غير المحلول",
    illustrationEn: "On January 4, 2012, a mysterious image appeared on the internet stating: 'We are looking for highly intelligent individuals. To find us, solve this.' What followed was the most elaborate, difficult cryptographic puzzle in human history, spanning data security, steganography, obscure literature, and physical clues hidden on telephone poles across the globe (from Moscow to Miami). The few who solved it vanished into the Dark Web, signing NDAs with an unknown, highly-funded global organization whose purpose, identity, and current activities remain an absolute mystery.",
    illustrationAr: "في ٤ يناير ٢٠١٢، ظهرت صورة غامضة على الإنترنت تقول: 'نحن نبحث عن أفراد أذكياء للغاية. للعثور علينا، قم بحل هذا.' ما تلا ذلك كان اللغز المشفر الأكثر تعقيداً وصعوبة في تاريخ البشرية، والذي يمتد عبر أمن البيانات، وإخفاء المعلومات، والأدب الغامض، والقرائن المادية المخبأة على أعمدة الهاتف في جميع أنحاء العالم. اختفى القلائل الذين تمكنوا من حله في الويب المظلم، ووقعوا اتفاقيات سرية مع منظمة عالمية مجهولة وممولة تمويلاً هائلاً، ولا يزال الغرض منها وهويتها وأنشطتها الحالية لغزاً مطلقاً."
  },
  {
    id: 903,
    title: "The Gateway Process",
    titleAr: "عملية البوابة",
    year: "1983",
    domain: "CIA Parapsychology",
    domainAr: "علم التخاطر الاستخباراتي",
    damage: "The Holographic Universe",
    damageAr: "الكون الهولوغرامي",
    illustrationEn: "A deeply terrifying OSINT discovery was the declassification of a 1983 CIA document titled 'Analysis and Assessment of Gateway Process'. The US military funded research into altering brainwave frequencies to detach consciousness from the physical body (astral projection) for espionage. The official intelligence report mathematically concludes that the universe is a giant, interacting holographic matrix of energy, and human consciousness can be weaponized to transcend time and space. The terror lies not in the theory, but in the fact that the most powerful military on earth treated it as operational physics.",
    illustrationAr: "من الاكتشافات المرعبة في المصادر المفتوحة كان رفع السرية عن وثيقة للمخابرات المركزية لعام ١٩٨٣ بعنوان 'تحليل وتقييم عملية البوابة'. مول الجيش الأمريكي أبحاثاً لتغيير ترددات الموجات الدماغية لفصل الوعي عن الجسد المادي للتجسس. خلص التقرير الاستخباراتي الرسمي رياضياً إلى أن الكون عبارة عن مصفوفة طاقة ثلاثية الأبعاد (هولوغرامية) ضخمة ومتفاعلة، وأنه يمكن تسليح الوعي البشري لتجاوز الزمان والمكان. الرعب لا يكمن في النظرية، بل في حقيقة أن أقوى جيش على وجه الأرض تعامل معها كفيزياء تشغيلية."
  },
  {
    id: 904,
    title: "The Dead Internet Theory",
    titleAr: "نظرية الإنترنت الميت",
    year: "2020s",
    domain: "Algorithmic Autonomy",
    domainAr: "استقلالية خوارزمية",
    damage: "Synthetic Reality",
    damageAr: "الواقع المُصنّع",
    illustrationEn: "OSINT researchers noticed a horrifying trend: genuine human interaction online is vanishing. The 'Dead Internet Theory' posits that the vast majority of current internet traffic, posts, and trends are generated entirely by interacting botnets and LLMs. We are scrolling through a synthetic echo chamber where AI generates content, other AIs reply to it, and AIs moderate it. Our entire cultural consensus, political outrage, and viral trends are no longer human, but the silent output of warring server farms.",
    illustrationAr: "لاحظ باحثو المصادر المفتوحة اتجاهاً مروعاً: التفاعل البشري الحقيقي على الإنترنت يتلاشى. تفترض 'نظرية الإنترنت الميت' أن الغالبية العظمى من حركة مرور الإنترنت والمشاركات والتريندات الحالية يتم إنشاؤها بالكامل بواسطة شبكات الروبوتات المتفاعلة (نماذج اللغة الكبيرة). نحن نتصفح غرفة صدى اصطناعية حيث يصنع الذكاء الاصطناعي المحتوى، ويرد عليه ذكاء اصطناعي آخر، ويراقبه ذكاء اصطناعي. إجماعنا الثقافي، وغضبنا السياسي، والتريندات الفيروسية لم تعد بشرية، بل هي المخرجات الصامتة لمزارع الخوادم المتحاربة."
  },
  {
    id: 905,
    title: "Havana Syndrome",
    titleAr: "متلازمة هافانا",
    year: "2016-Present",
    domain: "Directed Energy Weapons",
    domainAr: "أسلحة الطاقة الموجهة",
    damage: "Invisible Brain Trauma",
    damageAr: "صدمة دماغية خفية",
    illustrationEn: "Starting in Cuba, US and Canadian diplomats began experiencing sudden, inexplicable auditory sensations (a loud grinding noise) followed by severe cognitive decline, memory loss, and literal brain damage shown on MRI scans. The phenomenon spread globally to diplomats in China, Russia, and Washington DC. Extensive investigations point to a terrifying, unacknowledged reality: the covert deployment of directed pulsed-microwave energy weapons by a hostile state entity, capable of destroying a target's brain through a hotel wall without leaving a trace.",
    illustrationAr: "بدءاً من كوبا، بدأ الدبلوماسيون الأمريكيون والكنديون يعانون من أحاسيس سمعية مفاجئة لا يمكن تفسيرها (ضوضاء طحن عالية) يتبعها تدهور إدراكي شديد، وفقدان للذاكرة، وتلف حرفي في الدماغ يظهر في فحوصات التصوير بالرنين المغناطيسي. انتشرت الظاهرة عالمياً لتشمل دبلوماسيين في الصين وروسيا وواشنطن. تشير التحقيقات المكثفة إلى حقيقة مرعبة وغير معترف بها: النشر السري لأسلحة طاقة الميكروويف النبضية الموجهة من قبل كيان دولة معادية، قادرة على تدمير دماغ الهدف من خلال جدار غرفة الفندق دون ترك أي أثر."
  },
];
